// src/constants/businessAdminData.ts
import { LoaiDonItem, LichLamViecItem, BieuMauItem } from '../types/businessAdmin';

export const INITIAL_LOAI_DON_ITEMS: LoaiDonItem[] = [
  {
    id: 'to-cao',
    code: 'LD-TC',
    name: 'Tố cáo',
    description: 'Đơn tố cáo hành vi vi phạm pháp luật của cơ quan, tổ chức, cá nhân theo Luật Tố cáo 2018.',
    standardProcessingDays: 30,
    activeWorkflowId: 'wf-to-cao-01',
    activeWorkflowCode: 'QT-TC-2026-001',
    activeWorkflowName: 'Quy trình giải quyết đơn tố cáo',
    activeWorkflowVersion: 'v1.0',
    status: 'active',
    updatedAt: '19/09/2026',
    updatedBy: 'Nguyễn Minh Anh',
  },
  {
    id: 'khieu-nai',
    code: 'LD-KN',
    name: 'Khiếu nại',
    description: 'Đơn khiếu nại quyết định hành chính, hành vi hành chính của cơ quan nhà nước theo Luật Khiếu nại 2011.',
    standardProcessingDays: 30,
    activeWorkflowId: 'wf-khieu-nai-01',
    activeWorkflowCode: 'QT-KN-2026-002',
    activeWorkflowName: 'Quy trình giải quyết khiếu nại lần đầu',
    activeWorkflowVersion: 'v2.1',
    status: 'active',
    updatedAt: '15/09/2026',
    updatedBy: 'Trần Trọng Giáp',
  },
  {
    id: 'kien-nghi',
    code: 'LD-PA',
    name: 'Kiến nghị / Phản ánh',
    description: 'Kiến nghị, phản ánh về cơ chế, chính sách, thủ tục hành chính và thái độ phục vụ công vụ.',
    standardProcessingDays: 20,
    activeWorkflowId: 'wf-kien-nghi-01',
    activeWorkflowCode: 'QT-KNPA-2026-003',
    activeWorkflowName: 'Quy trình tiếp nhận và xử lý kiến nghị, phản ánh',
    activeWorkflowVersion: 'v1.0',
    status: 'active',
    updatedAt: '05/09/2026',
    updatedBy: 'Lê Văn Tuấn',
  },
  {
    id: 'tranh-chap',
    code: 'LD-DC',
    name: 'Tranh chấp đất đai',
    description: 'Đơn yêu cầu hòa giải tranh chấp đất đai tại UBND cấp xã/phường theo Luật Đất đai 2024.',
    standardProcessingDays: 45,
    activeWorkflowId: 'wf-tranh-chap-01',
    activeWorkflowCode: 'QT-TC-2026-004',
    activeWorkflowName: 'Quy trình hòa giải tranh chấp đất đai tại cấp xã',
    activeWorkflowVersion: 'v1.0',
    status: 'active',
    updatedAt: '18/09/2026',
    updatedBy: 'Hoàng Thị Hằng',
  },
  {
    id: 'khac',
    code: 'LD-ND',
    name: 'Đơn khác / Nặc danh',
    description: 'Đơn thư nặc danh, mạo danh hoặc đơn không thuộc các loại hình nghiệp vụ chính.',
    standardProcessingDays: 10,
    activeWorkflowId: 'wf-nac-danh-01',
    activeWorkflowCode: 'QT-ND-2025-099',
    activeWorkflowName: 'Quy trình xử lý đơn thư không rõ họ tên, nặc danh',
    activeWorkflowVersion: 'v1.0',
    status: 'inactive',
    updatedAt: '10/01/2026',
    updatedBy: 'Lê Văn Tuấn',
  },
];

export const INITIAL_LICH_LAM_VIEC_ITEMS: LichLamViecItem[] = [
  {
    id: 'sch-hanh-chinh',
    code: 'LLV-HC',
    name: 'Giờ hành chính Nhà nước',
    description: 'Áp dụng cho khối cơ quan chuyên môn và các phòng ban thụ lý hồ sơ hành chính.',
    workingDays: ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6'],
    morningHours: '08:00 - 12:00',
    afternoonHours: '13:30 - 17:30',
    isDefault: true,
    applicableDepartments: ['Bộ phận Tiếp nhận & Xử lý đơn', 'Đội Điều tra Kinh tế', 'Phòng Thanh tra - Pháp chế'],
    updatedAt: '01/09/2026',
  },
  {
    id: 'sch-mot-cua',
    code: 'LLV-MC',
    name: 'Lịch tiếp dân một cửa (Có sáng Thứ 7)',
    description: 'Lịch phục vụ tiếp công dân trực tiếp tại Bộ phận Một cửa, làm việc thêm sáng Thứ 7.',
    workingDays: ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Sáng Thứ 7'],
    morningHours: '07:30 - 11:30',
    afternoonHours: '13:00 - 17:00',
    isDefault: false,
    applicableDepartments: ['Bộ phận Tiếp công dân & Một cửa'],
    updatedAt: '10/08/2026',
  },
  {
    id: 'sch-24-7',
    code: 'LLV-247',
    name: 'Lịch trực ban 24/7 (Đường dây nóng)',
    description: 'Phục vụ tiếp nhận tin báo khẩn cấp qua cổng dịch vụ công trực tuyến và hotline liên tục.',
    workingDays: ['Tất cả các ngày trong tuần (24/7)'],
    morningHours: '00:00 - 12:00',
    afternoonHours: '12:00 - 24:00',
    isDefault: false,
    applicableDepartments: ['Tổ thường trực trực ban'],
    updatedAt: '15/07/2026',
  },
  {
    id: 'sch-truc-chien',
    code: 'LLV-TC',
    name: 'Lịch trực chiến cao điểm',
    description: 'Áp dụng trong các đợt cao điểm giải quyết khiếu kiện đông người hoặc kỳ họp quan trọng.',
    workingDays: ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7', 'Chủ Nhật'],
    morningHours: '07:00 - 12:00',
    afternoonHours: '13:00 - 21:00',
    isDefault: false,
    applicableDepartments: ['Tổ công tác liên ngành giải quyết khiếu nại tố cáo'],
    updatedAt: '01/06/2026',
  },
];

export const INITIAL_BIEU_MAU_ITEMS: BieuMauItem[] = [
  {
    id: 'bm-01',
    code: 'BM-01/TN',
    name: 'Giấy tiếp nhận hồ sơ và hẹn trả kết quả',
    loaiDonId: 'all',
    loaiDonName: 'Áp dụng chung tất cả loại đơn',
    applicableStepName: 'Tiếp nhận & Vào sổ thụ lý',
    fileFormat: 'DOCX',
    fileSize: '48 KB',
    status: 'active',
    version: 'v2.0',
    updatedAt: '12/09/2026',
    updatedBy: 'Nguyễn Minh Anh',
  },
  {
    id: 'bm-02',
    code: 'BM-02/XM',
    name: 'Kế hoạch xác minh nội dung tố cáo',
    loaiDonId: 'to-cao',
    loaiDonName: 'Tố cáo',
    applicableStepName: 'Xác minh nội dung tố cáo',
    fileFormat: 'DOCX',
    fileSize: '65 KB',
    status: 'active',
    version: 'v1.2',
    updatedAt: '15/09/2026',
    updatedBy: 'Nguyễn Minh Anh',
  },
  {
    id: 'bm-03',
    code: 'BM-03/XM',
    name: 'Biên bản ghi nhận lời khai người tố cáo / đương sự',
    loaiDonId: 'to-cao',
    loaiDonName: 'Tố cáo',
    applicableStepName: 'Xác minh nội dung tố cáo',
    fileFormat: 'DOCX',
    fileSize: '52 KB',
    status: 'active',
    version: 'v1.0',
    updatedAt: '10/09/2026',
    updatedBy: 'Nguyễn Minh Anh',
  },
  {
    id: 'bm-04',
    code: 'BM-04/DX',
    name: 'Tờ trình xem xét kết luận giải quyết tố cáo',
    loaiDonId: 'to-cao',
    loaiDonName: 'Tố cáo',
    applicableStepName: 'Đề xuất hướng xử lý',
    fileFormat: 'DOCX',
    fileSize: '70 KB',
    status: 'active',
    version: 'v1.0',
    updatedAt: '18/09/2026',
    updatedBy: 'Trần Trọng Giáp',
  },
  {
    id: 'bm-05',
    code: 'BM-05/PD',
    name: 'Phiếu phê duyệt dự thảo kết luận của Lãnh đạo',
    loaiDonId: 'to-cao',
    loaiDonName: 'Tố cáo',
    applicableStepName: 'Trình lãnh đạo phê duyệt',
    fileFormat: 'PDF',
    fileSize: '36 KB',
    status: 'active',
    version: 'v1.0',
    updatedAt: '18/09/2026',
    updatedBy: 'Lãnh đạo đơn vị',
  },
  {
    id: 'bm-06',
    code: 'BM-06/KL',
    name: 'Kết luận nội dung tố cáo chính thức',
    loaiDonId: 'to-cao',
    loaiDonName: 'Tố cáo',
    applicableStepName: 'Kết luận nội dung tố cáo',
    fileFormat: 'DOCX',
    fileSize: '110 KB',
    status: 'active',
    version: 'v2.1',
    updatedAt: '19/09/2026',
    updatedBy: 'Thủ trưởng cơ quan',
  },
  {
    id: 'bm-07',
    code: 'BM-07/TB',
    name: 'Thông báo kết luận giải quyết tố cáo gửi công dân',
    loaiDonId: 'to-cao',
    loaiDonName: 'Tố cáo',
    applicableStepName: 'Thông báo kết quả và lưu hồ sơ',
    fileFormat: 'PDF',
    fileSize: '42 KB',
    status: 'active',
    version: 'v1.0',
    updatedAt: '19/09/2026',
    updatedBy: 'Văn thư',
  },
  {
    id: 'bm-kn-01',
    code: 'BM-KN-01',
    name: 'Thông báo thụ lý giải quyết khiếu nại lần đầu',
    loaiDonId: 'khieu-nai',
    loaiDonName: 'Khiếu nại',
    applicableStepName: 'Tiếp nhận đơn khiếu nại',
    fileFormat: 'DOCX',
    fileSize: '58 KB',
    status: 'active',
    version: 'v2.0',
    updatedAt: '12/09/2026',
    updatedBy: 'Trần Trọng Giáp',
  },
  {
    id: 'bm-kn-03',
    code: 'BM-KN-03',
    name: 'Biên bản đối thoại khiếu nại công khai',
    loaiDonId: 'khieu-nai',
    loaiDonName: 'Khiếu nại',
    applicableStepName: 'Tổ chức đối thoại',
    fileFormat: 'DOCX',
    fileSize: '62 KB',
    status: 'active',
    version: 'v2.1',
    updatedAt: '15/09/2026',
    updatedBy: 'Trần Trọng Giáp',
  },
  {
    id: 'bm-dc-02',
    code: 'BM-DC-02',
    name: 'Biên bản kiểm tra hiện trạng và ranh giới thửa đất',
    loaiDonId: 'tranh-chap',
    loaiDonName: 'Tranh chấp đất đai',
    applicableStepName: 'Xác minh hiện trạng ranh giới',
    fileFormat: 'XLSX',
    fileSize: '95 KB',
    status: 'active',
    version: 'v1.0',
    updatedAt: '18/09/2026',
    updatedBy: 'Hoàng Thị Hằng',
  },
];
