// src/constants/processWorkflows.ts
import { ProcessWorkflow } from '../types/workflowConfig';

export const INITIAL_PROCESS_WORKFLOWS: ProcessWorkflow[] = [
  {
    id: 'wf-to-cao-01',
    code: 'QT-TC-2026-001',
    name: 'Quy trình giải quyết đơn tố cáo',
    loaiDonId: 'to-cao',
    loaiDonName: 'Tố cáo',
    version: 'v1.0',
    status: 'draft',
    isLatestForLoaiDon: true,
    description: 'Quy trình chuẩn áp dụng cho công tác tiếp nhận, xác minh nội dung tố cáo, lập tờ trình đề xuất và ban hành kết luận giải quyết tố cáo theo Luật Tố cáo 2018.',
    updatedAt: '19/09/2026 15:30',
    updatedBy: 'Nguyễn Minh Anh (Cán bộ thụ lý)',
    effectiveDate: '01/10/2026',
    lanes: [
      { id: 'lane-van-thu', name: 'Văn thư', code: 'VT', order: 1, description: 'Bộ phận Văn thư / Tiếp nhận một cửa' },
      { id: 'lane-chuyen-mon', name: 'Chuyên môn', code: 'CM', order: 2, description: 'Tổ công tác / Cán bộ chuyên môn thụ lý hồ sơ' },
      { id: 'lane-lanh-dao', name: 'Lãnh đạo', code: 'LD', order: 3, description: 'Lãnh đạo đơn vị / Thủ trưởng cơ quan có thẩm quyền' },
    ],
    stages: [
      { id: 'stage-tiep-nhan', name: 'Tiếp nhận tố cáo', order: 1 },
      { id: 'stage-xac-minh', name: 'Xác minh nội dung tố cáo', order: 2 },
      { id: 'stage-de-xuat', name: 'Đề xuất hướng xử lý', order: 3 },
      { id: 'stage-ket-luan', name: 'Kết luận nội dung tố cáo', order: 4 },
      { id: 'stage-thong-bao-luu-tru', name: 'Thông báo kết quả và lưu hồ sơ', order: 5 },
    ],
    steps: [
      {
        id: 'step-tc-01',
        code: 'STEP-TC-01',
        name: 'Tiếp nhận tố cáo',
        laneId: 'lane-van-thu',
        stageId: 'stage-tiep-nhan',
        description: 'Tiếp nhận đơn, đối chiếu giấy tờ pháp lý của người nộp đơn và vào sổ tiếp nhận tố cáo.',
        isStart: true,
        isEnd: false,
        timeLimitDays: 1,
        workHours: 8,
        warningBeforeHours: 2,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Giấy biên nhận đơn', 'Phiếu tiếp nhận tố cáo'],
        stepForms: ['BM-01/TN Giấy hẹn trả kết quả tiếp nhận'],
        statusChangeDoc: 'Quyết định thụ lý tố cáo',
      },
      {
        id: 'step-tc-02',
        code: 'STEP-TC-02',
        name: 'Xác minh nội dung tố cáo',
        laneId: 'lane-chuyen-mon',
        stageId: 'stage-xac-minh',
        description: 'Kiểm tra căn cứ pháp lý, đối chiếu chứng cứ, làm việc trực tiếp với người tố cáo và các bên có liên quan.',
        isStart: false,
        isEnd: false,
        timeLimitDays: 15,
        workHours: 120,
        warningBeforeHours: 24,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Biên bản làm việc với người tố cáo', 'Tài liệu xác minh thực tế', 'Văn bản tra soát tài liệu'],
        stepForms: ['BM-02/XM Kế hoạch xác minh nội dung tố cáo', 'BM-03/XM Biên bản ghi nhận lời khai'],
        statusChangeDoc: 'Thông báo về việc thụ lý và phân công xác minh',
      },
      {
        id: 'step-tc-03',
        code: 'STEP-TC-03',
        name: 'Đề xuất hướng xử lý',
        laneId: 'lane-chuyen-mon',
        stageId: 'stage-de-xuat',
        description: 'Lập báo cáo kết quả xác minh nội dung tố cáo và dự thảo tờ trình phương án kết luận xử lý.',
        isStart: false,
        isEnd: false,
        timeLimitDays: 5,
        workHours: 40,
        warningBeforeHours: 8,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Báo cáo kết quả xác minh nội dung tố cáo', 'Tờ trình đề xuất xử lý'],
        stepForms: ['BM-04/DX Tờ trình xem xét kết luận giải quyết tố cáo'],
        statusChangeDoc: 'Phiếu trình duyệt lãnh đạo',
      },
      {
        id: 'step-tc-04',
        code: 'STEP-TC-04',
        name: 'Trình lãnh đạo phê duyệt',
        laneId: 'lane-lanh-dao',
        stageId: 'stage-de-xuat',
        description: 'Lãnh đạo xem xét hồ sơ, báo cáo xác minh và tờ trình đề xuất. Quyết định đồng ý ban hành kết luận hoặc yêu cầu xác minh bổ sung.',
        isStart: false,
        isEnd: false,
        timeLimitDays: 3,
        workHours: 24,
        warningBeforeHours: 4,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Ý kiến chỉ đạo của Lãnh đạo', 'Phiếu thẩm định hồ sơ'],
        stepForms: ['BM-05/PD Phiếu phê duyệt dự thảo kết luận'],
        statusChangeDoc: 'Ý kiến chỉ đạo của Thủ trưởng cơ quan',
      },
      {
        id: 'step-tc-05',
        code: 'STEP-TC-05',
        name: 'Kết luận nội dung tố cáo',
        laneId: 'lane-lanh-dao',
        stageId: 'stage-ket-luan',
        description: 'Ký ban hành Kết luận nội dung tố cáo chính thức và các quyết định xử lý kỷ luật/chuyển cơ quan điều tra (nếu có dấu hiệu vi phạm pháp luật).',
        isStart: false,
        isEnd: false,
        timeLimitDays: 2,
        workHours: 16,
        warningBeforeHours: 4,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Kết luận nội dung tố cáo (Bản chính thức có chữ ký số)'],
        stepForms: ['BM-06/KL Kết luận nội dung tố cáo theo mẫu chuẩn'],
        statusChangeDoc: 'Kết luận nội dung tố cáo chính thức',
      },
      {
        id: 'step-tc-06',
        code: 'STEP-TC-06',
        name: 'Thông báo kết quả và lưu hồ sơ',
        laneId: 'lane-van-thu',
        stageId: 'stage-thong-bao-luu-tru',
        description: 'Phát hành thông báo kết luận giải quyết tố cáo gửi người tố cáo, người bị tố cáo và cơ quan cấp trên; đóng hồ sơ lưu trữ theo quy định.',
        isStart: false,
        isEnd: true,
        timeLimitDays: 2,
        workHours: 16,
        warningBeforeHours: 4,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Sổ theo dõi gửi phát hành văn bản', 'Mục lục hồ sơ lưu trữ'],
        stepForms: ['BM-07/TB Thông báo kết luận giải quyết tố cáo gửi công dân'],
        statusChangeDoc: 'Quyết định đóng hồ sơ và lưu trữ',
      },
    ],
    transitions: [
      {
        id: 'trans-01',
        actionName: 'Chuyển xác minh',
        fromStepId: 'step-tc-01',
        toStepId: 'step-tc-02',
        type: 'normal',
        allowedRoles: ['Cán bộ Văn thư', 'Cán bộ Tiếp nhận'],
        createNextTask: true,
        taskAssigneeRole: 'Tổ công tác Chuyên môn',
        warningMessage: 'Hồ sơ chưa có đủ giấy tờ định danh hoặc chưa xác thực đơn thư hợp lệ.',
        conditions: [
          {
            id: 'cond-1',
            logicOp: 'AND',
            fieldSource: 'loai_don',
            fieldName: 'Loại đơn',
            operator: '=',
            value: 'Tố cáo',
          },
          {
            id: 'cond-2',
            logicOp: 'AND',
            fieldSource: 'trang_thai',
            fieldName: 'Trạng thái',
            operator: '=',
            value: 'Đã thụ lý',
          },
          {
            id: 'cond-3',
            logicOp: 'AND',
            fieldSource: 'tham_quyen',
            fieldName: 'Thẩm quyền',
            operator: '=',
            value: 'Đúng thẩm quyền',
          },
        ],
      },
      {
        id: 'trans-02',
        actionName: 'Lập đề xuất',
        fromStepId: 'step-tc-02',
        toStepId: 'step-tc-03',
        type: 'normal',
        allowedRoles: ['Cán bộ thụ lý', 'Thành viên Tổ xác minh'],
        createNextTask: true,
        taskAssigneeRole: 'Cán bộ Chuyên môn',
        warningMessage: 'Chưa có đầy đủ biên bản làm việc hoặc báo cáo đối soát xác minh.',
        conditions: [
          {
            id: 'cond-4',
            logicOp: 'AND',
            fieldSource: 'van_ban',
            fieldName: 'Biên bản làm việc',
            operator: 'co_gia_tri',
            value: '',
          },
        ],
      },
      {
        id: 'trans-03',
        actionName: 'Trình lãnh đạo',
        fromStepId: 'step-tc-03',
        toStepId: 'step-tc-04',
        type: 'normal',
        allowedRoles: ['Trưởng phòng Chuyên môn', 'Cán bộ thụ lý'],
        createNextTask: true,
        taskAssigneeRole: 'Lãnh đạo đơn vị',
        warningMessage: 'Chưa đính kèm dự thảo tờ trình xem xét phê duyệt.',
        conditions: [
          {
            id: 'cond-5',
            logicOp: 'AND',
            fieldSource: 'bieu_mau',
            fieldName: 'Tờ trình phê duyệt',
            operator: 'co_gia_tri',
            value: '',
          },
        ],
      },
      {
        id: 'trans-04',
        actionName: 'Trả lại (Yêu cầu xác minh bổ sung)',
        fromStepId: 'step-tc-04',
        toStepId: 'step-tc-02',
        type: 'return',
        allowedRoles: ['Lãnh đạo đơn vị', 'Thủ trưởng cơ quan'],
        createNextTask: true,
        taskAssigneeRole: 'Tổ công tác Chuyên môn',
        warningMessage: 'Cần ghi rõ nội dung yêu cầu cán bộ xác minh bổ sung chứng cứ.',
        conditions: [
          {
            id: 'cond-6',
            logicOp: 'OR',
            fieldSource: 'ket_qua',
            fieldName: 'Ý kiến phê duyệt',
            operator: '=',
            value: 'Yêu cầu xác minh lại',
          },
        ],
      },
      {
        id: 'trans-05',
        actionName: 'Đồng ý & Ký kết luận',
        fromStepId: 'step-tc-04',
        toStepId: 'step-tc-05',
        type: 'normal',
        allowedRoles: ['Lãnh đạo đơn vị', 'Thủ trưởng cơ quan'],
        createNextTask: true,
        taskAssigneeRole: 'Lãnh đạo đơn vị',
        warningMessage: 'Cần chữ ký phê duyệt của người có thẩm quyền.',
        conditions: [
          {
            id: 'cond-7',
            logicOp: 'AND',
            fieldSource: 'ket_qua',
            fieldName: 'Kết quả thẩm định',
            operator: '=',
            value: 'Đồng ý phê duyệt',
          },
        ],
      },
      {
        id: 'trans-06',
        actionName: 'Chuyển thông báo & lưu trữ',
        fromStepId: 'step-tc-05',
        toStepId: 'step-tc-06',
        type: 'normal',
        allowedRoles: ['Thư ký Lãnh đạo', 'Văn phòng'],
        createNextTask: true,
        taskAssigneeRole: 'Bộ phận Văn thư',
        warningMessage: 'Văn bản kết luận chưa được cấp số hoặc chưa có chữ ký số hợp lệ.',
        conditions: [
          {
            id: 'cond-8',
            logicOp: 'AND',
            fieldSource: 'van_ban',
            fieldName: 'Số ký hiệu văn bản',
            operator: 'co_gia_tri',
            value: '',
          },
        ],
      },
    ],
    versionHistory: [
      {
        version: 'v1.0',
        publishedAt: 'Chưa phát hành (Bản nháp hiện tại)',
        publishedBy: 'Nguyễn Minh Anh',
        role: 'Cán bộ thụ lý hồ sơ',
        notes: 'Thiết kế cấu trúc quy trình xử lý đơn tố cáo chuẩn hóa theo Luật Tố cáo 2018.',
        canCuPhapLy: 'Luật Tố cáo số 25/2018/QH14; Nghị định số 31/2019/NĐ-CP quy định chi tiết một số điều của Luật Tố cáo.',
        isCurrentActive: true,
        totalSteps: 5,
        slaDays: 20,
        lanesCount: 3,
        formsCount: 3,
        changes: [
          {
            type: 'add',
            title: 'Khởi tạo luồng xử lý đơn tố cáo chuẩn hóa',
            description: 'Thiết lập 5 bước nghiệp vụ từ tiếp nhận, phân loại, xác minh điều kiện thụ lý đến ban hành kết luận.',
            target: 'Toàn bộ quy trình',
          },
          {
            type: 'add',
            title: 'Bổ sung bước bảo mật thông tin người tố cáo',
            description: 'Tự động mã hóa thông tin người đứng đơn, áp dụng chế độ bảo mật nghiêm ngặt.',
            target: 'Bước STEP-TC-01',
          },
        ],
      },
    ],
  },
  {
    id: 'wf-khieu-nai-01',
    code: 'QT-KN-2026-002',
    name: 'Quy trình giải quyết khiếu nại lần đầu',
    loaiDonId: 'khieu-nai',
    loaiDonName: 'Khiếu nại',
    version: 'v2.1',
    status: 'published',
    isLatestForLoaiDon: true,
    description: 'Quy trình tiếp nhận, thụ lý và đối thoại, ban hành quyết định giải quyết khiếu nại lần đầu theo Luật Khiếu nại 2011.',
    updatedAt: '12/09/2026 09:15',
    updatedBy: 'Trần Trọng Giáp (Trưởng phòng)',
    effectiveDate: '15/09/2026',
    lanes: [
      { id: 'lane-vt', name: 'Văn thư', code: 'VT', order: 1 },
      { id: 'lane-cm', name: 'Chuyên môn', code: 'CM', order: 2 },
      { id: 'lane-ld', name: 'Lãnh đạo', code: 'LD', order: 3 },
    ],
    stages: [
      { id: 'stg-1', name: 'Tiếp nhận đơn', order: 1 },
      { id: 'stg-2', name: 'Thụ lý & Xác minh', order: 2 },
      { id: 'stg-3', name: 'Tổ chức đối thoại', order: 3 },
      { id: 'stg-4', name: 'Ban hành quyết định', order: 4 },
      { id: 'stg-5', name: 'Gửi kết quả & Lưu trữ', order: 5 },
    ],
    steps: [
      {
        id: 'st-kn-1',
        code: 'STEP-KN-01',
        name: 'Tiếp nhận đơn khiếu nại',
        laneId: 'lane-vt',
        stageId: 'stg-1',
        description: 'Kiểm tra điều kiện thụ lý khiếu nại, vào sổ theo dõi.',
        isStart: true,
        isEnd: false,
        timeLimitDays: 2,
        workHours: 16,
        warningBeforeHours: 4,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Giấy biên nhận đơn khiếu nại'],
        stepForms: ['BM-KN-01'],
        statusChangeDoc: 'Thông báo thụ lý khiếu nại',
      },
      {
        id: 'st-kn-2',
        code: 'STEP-KN-02',
        name: 'Xác minh nội dung khiếu nại',
        laneId: 'lane-cm',
        stageId: 'stg-2',
        description: 'Thu thập hồ sơ địa chính, làm việc với người khiếu nại.',
        isStart: false,
        isEnd: false,
        timeLimitDays: 20,
        workHours: 160,
        warningBeforeHours: 32,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Biên bản thẩm tra xác minh'],
        stepForms: ['BM-KN-02'],
        statusChangeDoc: 'Báo cáo xác minh khiếu nại',
      },
      {
        id: 'st-kn-3',
        code: 'STEP-KN-03',
        name: 'Tổ chức đối thoại',
        laneId: 'lane-cm',
        stageId: 'stg-3',
        description: 'Chủ trì đối thoại trực tiếp công khai với người khiếu nại.',
        isStart: false,
        isEnd: false,
        timeLimitDays: 5,
        workHours: 40,
        warningBeforeHours: 8,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Biên bản đối thoại khiếu nại có chữ ký các bên'],
        stepForms: ['BM-KN-03'],
        statusChangeDoc: 'Biên bản đối thoại',
      },
      {
        id: 'st-kn-4',
        code: 'STEP-KN-04',
        name: 'Ban hành Quyết định giải quyết khiếu nại',
        laneId: 'lane-ld',
        stageId: 'stg-4',
        description: 'Chủ tịch UBND / Thủ trưởng cơ quan ký ban hành Quyết định.',
        isStart: false,
        isEnd: false,
        timeLimitDays: 3,
        workHours: 24,
        warningBeforeHours: 4,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Quyết định giải quyết khiếu nại'],
        stepForms: ['BM-KN-04'],
        statusChangeDoc: 'Quyết định giải quyết khiếu nại lần đầu',
      },
      {
        id: 'st-kn-5',
        code: 'STEP-KN-05',
        name: 'Tống đạt quyết định & Lưu hồ sơ',
        laneId: 'lane-vt',
        stageId: 'stg-5',
        description: 'Tống đạt quyết định cho các đương sự, lưu vào kho lưu trữ.',
        isStart: false,
        isEnd: true,
        timeLimitDays: 2,
        workHours: 16,
        warningBeforeHours: 4,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Biên bản giao nhận quyết định', 'Hồ sơ lưu trữ'],
        stepForms: ['BM-KN-05'],
        statusChangeDoc: 'Biên bản tống đạt',
      },
    ],
    transitions: [
      {
        id: 'tr-kn-1',
        actionName: 'Chuyển thụ lý xác minh',
        fromStepId: 'st-kn-1',
        toStepId: 'st-kn-2',
        type: 'normal',
        allowedRoles: ['Cán bộ Văn thư'],
        createNextTask: true,
        taskAssigneeRole: 'Tổ Chuyên môn',
        conditions: [
          {
            id: 'c-kn-1',
            logicOp: 'AND',
            fieldSource: 'loai_don',
            fieldName: 'Loại đơn',
            operator: '=',
            value: 'Khiếu nại',
          },
        ],
      },
      {
        id: 'tr-kn-2',
        actionName: 'Lên lịch đối thoại',
        fromStepId: 'st-kn-2',
        toStepId: 'st-kn-3',
        type: 'normal',
        allowedRoles: ['Cán bộ thụ lý'],
        createNextTask: true,
        taskAssigneeRole: 'Tổ Chuyên môn',
        conditions: [],
      },
      {
        id: 'tr-kn-3',
        actionName: 'Trình ký quyết định',
        fromStepId: 'st-kn-3',
        toStepId: 'st-kn-4',
        type: 'normal',
        allowedRoles: ['Trưởng phòng Chuyên môn'],
        createNextTask: true,
        taskAssigneeRole: 'Lãnh đạo',
        conditions: [],
      },
      {
        id: 'tr-kn-4',
        actionName: 'Chuyển tống đạt',
        fromStepId: 'st-kn-4',
        toStepId: 'st-kn-5',
        type: 'normal',
        allowedRoles: ['Văn phòng'],
        createNextTask: true,
        taskAssigneeRole: 'Văn thư',
        conditions: [],
      },
    ],
    versionHistory: [
      {
        version: 'v2.1',
        publishedAt: '15/09/2026',
        publishedBy: 'Trần Trọng Giáp',
        role: 'Trưởng phòng Nghiệp vụ',
        notes: 'Cập nhật bổ sung bước Đối thoại bắt buộc và số hóa biểu mẫu biên bản đối thoại điện tử theo Nghị định 124/2020/NĐ-CP.',
        canCuPhapLy: 'Nghị định 124/2020/NĐ-CP quy định chi tiết một số điều của Luật Khiếu nại; Thông tư 04/2021/TT-TTCP.',
        isCurrentActive: true,
        totalSteps: 5,
        slaDays: 28,
        lanesCount: 3,
        formsCount: 4,
        changes: [
          {
            type: 'add',
            title: 'Bổ sung bước STEP-KN-03: Tổ chức đối thoại',
            description: 'Tổ chức đối thoại trực tiếp hoặc trực tuyến với người khiếu nại trước khi ban hành quyết định giải quyết.',
            target: 'Giai đoạn 3: Đối thoại',
          },
          {
            type: 'add',
            title: 'Bổ sung biểu mẫu BM-KN-03: Biên bản đối thoại giải quyết khiếu nại',
            description: 'Mẫu biên bản số hóa chuẩn có chữ ký số của các bên tham gia đối thoại.',
            target: 'Biểu mẫu quy chuẩn',
          },
          {
            type: 'modify',
            title: 'Cập nhật điều kiện chuyển tiếp sang bước Ra quyết định',
            description: 'Bắt buộc phải có Biên bản đối thoại đã ký trước khi Lãnh đạo ký Quyết định giải quyết.',
            target: 'Điều kiện chuyển tiếp TRANS-KN-03',
          },
        ],
      },
      {
        version: 'v2.0',
        publishedAt: '01/06/2026',
        publishedBy: 'Trần Trọng Giáp',
        role: 'Trưởng phòng Nghiệp vụ',
        notes: 'Tối ưu hóa thời gian thụ lý và xác minh nội dung khiếu nại, giảm 10 ngày so với quy trình cũ.',
        canCuPhapLy: 'Kế hoạch cải cách thủ tục hành chính số 45/KH-UBND của UBND tỉnh.',
        isCurrentActive: false,
        totalSteps: 4,
        slaDays: 30,
        lanesCount: 3,
        formsCount: 3,
        changes: [
          {
            type: 'modify',
            title: 'Rút ngắn thời hạn bước Xác minh nội dung',
            description: 'Giảm thời hạn từ 30 ngày xuống 20 ngày làm việc đối với vụ việc thông thường.',
            target: 'Bước STEP-KN-02',
          },
          {
            type: 'add',
            title: 'Tự động gửi thông báo SMS / VNeID cho công dân khi thụ lý',
            description: 'Tích hợp cổng dịch vụ công thông báo tiến độ xử lý hồ sơ tự động.',
            target: 'Bước STEP-KN-01',
          },
        ],
      },
      {
        version: 'v1.0',
        publishedAt: '10/01/2026',
        publishedBy: 'Nguyễn Minh Anh',
        role: 'Chuyên viên thụ lý hồ sơ',
        notes: 'Phiên bản ban hành lần đầu áp dụng trên nền tảng GOVEX.',
        canCuPhapLy: 'Luật Khiếu nại số 02/2011/QH13.',
        isCurrentActive: false,
        totalSteps: 4,
        slaDays: 40,
        lanesCount: 3,
        formsCount: 2,
        changes: [
          {
            type: 'add',
            title: 'Khởi tạo luồng giải quyết khiếu nại lần đầu',
            description: 'Xây dựng 4 bước cơ bản: Tiếp nhận -> Xác minh -> Quyết định -> Trả kết quả.',
            target: 'Cấu hình ban đầu',
          },
        ],
      },
    ],
    activeDonsCount: 68,
    auditLogs: [
      {
        id: 'log-kn-01',
        timestamp: '15/09/2026 14:35',
        authorName: 'Trần Trọng Giáp',
        authorRole: 'Trưởng phòng Nghiệp vụ',
        actionType: 'create_step',
        actionLabel: 'Tạo bước xử lý mới',
        targetName: 'Tổ chức đối thoại (STEP-KN-03)',
        targetId: 'st-kn-3',
        targetType: 'step',
        beforeValue: 'Chưa có bước',
        afterValue: 'Tên: Tổ chức đối thoại | Làn: Lãnh đạo | Giai đoạn: Đối thoại | Hạn: 3 ngày',
        notes: 'Bổ sung bước đối thoại bắt buộc theo Nghị định 124/2020/NĐ-CP',
      },
      {
        id: 'log-kn-02',
        timestamp: '15/09/2026 10:15',
        authorName: 'Nguyễn Minh Anh',
        authorRole: 'Chuyên viên thụ lý hồ sơ',
        actionType: 'edit_step',
        actionLabel: 'Chỉnh sửa bước xử lý',
        targetName: 'Xác minh nội dung khiếu nại (STEP-KN-02)',
        targetId: 'st-kn-2',
        targetType: 'step',
        beforeValue: 'Nhóm chịu trách nhiệm = Văn thư (VT)',
        afterValue: 'Nhóm chịu trách nhiệm = Chuyên môn (CM)',
        notes: 'Chuyển quyền thẩm tra xác minh hồ sơ về bộ phận Chuyên môn phụ trách',
      },
      {
        id: 'log-kn-03',
        timestamp: '14/09/2026 16:20',
        authorName: 'Nguyễn Minh Anh',
        authorRole: 'Chuyên viên thụ lý hồ sơ',
        actionType: 'change_sla',
        actionLabel: 'Thay đổi thời hạn SLA',
        targetName: 'Xác minh nội dung khiếu nại (STEP-KN-02)',
        targetId: 'st-kn-2',
        targetType: 'step',
        beforeValue: 'Thời hạn: 30 ngày làm việc (240 giờ)',
        afterValue: 'Thời hạn: 20 ngày làm việc (160 giờ)',
        notes: 'Rút ngắn thời hạn thụ lý vụ việc theo chỉ đạo cải cách hành chính',
      },
      {
        id: 'log-kn-04',
        timestamp: '14/09/2026 09:40',
        authorName: 'Trần Trọng Giáp',
        authorRole: 'Trưởng phòng Nghiệp vụ',
        actionType: 'edit_condition',
        actionLabel: 'Sửa điều kiện đường chuyển',
        targetName: 'Đối thoại → Ban hành quyết định (TRANS-KN-03)',
        targetId: 'tr-kn-3',
        targetType: 'transition',
        beforeValue: 'Không có điều kiện ràng buộc',
        afterValue: 'Có biên bản đối thoại = ĐÃ KÝ VÀ LƯU TRỮ (AND)',
        notes: 'Bắt buộc phải hoàn tất biên bản đối thoại mới cho phép chuyển bước ra quyết định',
      },
      {
        id: 'log-kn-05',
        timestamp: '12/09/2026 15:30',
        authorName: 'Lê Văn Tuấn',
        authorRole: 'Cán bộ Một cửa',
        actionType: 'change_form',
        actionLabel: 'Bổ sung biểu mẫu quy chuẩn',
        targetName: 'Tiếp nhận đơn khiếu nại (STEP-KN-01)',
        targetId: 'st-kn-1',
        targetType: 'step',
        beforeValue: 'Biểu mẫu: BM-KN-01 (Giấy biên nhận)',
        afterValue: 'Biểu mẫu: BM-KN-01 (Giấy biên nhận) + Mẫu số 02 (Thông báo thụ lý)',
        notes: 'Chuẩn hóa biểu mẫu điện tử liên thông Cổng Dịch vụ công',
      },
    ],
  },
  {
    id: 'wf-kien-nghi-01',
    code: 'QT-KNPA-2026-003',
    name: 'Quy trình tiếp nhận và xử lý kiến nghị, phản ánh',
    loaiDonId: 'kien-nghi',
    loaiDonName: 'Kiến nghị / Phản ánh',
    version: 'v1.0',
    status: 'published',
    isLatestForLoaiDon: true,
    description: 'Quy trình giải quyết kiến nghị phản ánh của tổ chức, cá nhân qua cổng dịch vụ công và tiếp nhận trực tiếp.',
    updatedAt: '05/09/2026 11:20',
    updatedBy: 'Lê Văn Tuấn (Phó Chánh Văn phòng)',
    effectiveDate: '01/09/2026',
    lanes: [
      { id: 'l1', name: 'Văn thư', code: 'VT', order: 1 },
      { id: 'l2', name: 'Chuyên môn', code: 'CM', order: 2 },
    ],
    stages: [
      { id: 'st-1', name: 'Tiếp nhận', order: 1 },
      { id: 'st-2', name: 'Xử lý kiến nghị', order: 2 },
      { id: 'st-3', name: 'Trả lời công dân', order: 3 },
    ],
    steps: [
      {
        id: 's-knpa-1',
        code: 'STEP-PA-01',
        name: 'Tiếp nhận phản ánh',
        laneId: 'l1',
        stageId: 'st-1',
        isStart: true,
        isEnd: false,
        timeLimitDays: 1,
        workHours: 8,
        warningBeforeHours: 2,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Phiếu tiếp nhận phản ánh'],
        stepForms: ['BM-PA-01'],
        statusChangeDoc: 'Phiếu chuyển phản ánh',
      },
      {
        id: 's-knpa-2',
        code: 'STEP-PA-02',
        name: 'Xử lý và lập văn bản trả lời',
        laneId: 'l2',
        stageId: 'st-2',
        isStart: false,
        isEnd: false,
        timeLimitDays: 5,
        workHours: 40,
        warningBeforeHours: 8,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Văn bản giải quyết kiến nghị'],
        stepForms: ['BM-PA-02'],
        statusChangeDoc: 'Công văn trả lời công dân',
      },
      {
        id: 's-knpa-3',
        code: 'STEP-PA-03',
        name: 'Gửi văn bản trả lời và công khai',
        laneId: 'l1',
        stageId: 'st-3',
        isStart: false,
        isEnd: true,
        timeLimitDays: 1,
        workHours: 8,
        warningBeforeHours: 2,
        workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
        storedDocuments: ['Biên nhận bưu điện', 'Bản đăng cổng TTĐT'],
        stepForms: ['BM-PA-03'],
        statusChangeDoc: 'Thông báo kết quả phản ánh',
      },
    ],
    transitions: [
      {
        id: 'tr-pa-1',
        actionName: 'Chuyển xử lý',
        fromStepId: 's-knpa-1',
        toStepId: 's-knpa-2',
        type: 'normal',
        allowedRoles: ['Văn thư'],
        createNextTask: true,
        taskAssigneeRole: 'Chuyên môn',
        conditions: [],
      },
      {
        id: 'tr-pa-2',
        actionName: 'Phát hành trả lời',
        fromStepId: 's-knpa-2',
        toStepId: 's-knpa-3',
        type: 'normal',
        allowedRoles: ['Chuyên môn'],
        createNextTask: true,
        taskAssigneeRole: 'Văn thư',
        conditions: [],
      },
    ],
    versionHistory: [
      {
        version: 'v1.0',
        publishedAt: '01/09/2026',
        publishedBy: 'Lê Văn Tuấn',
        role: 'Cán bộ Một cửa',
        notes: 'Ban hành lần đầu theo Quyết định chuẩn hóa tiếp nhận kiến nghị phản ánh.',
        canCuPhapLy: 'Nghị định 20/2008/NĐ-CP về tiếp nhận, xử lý phản ánh, kiến nghị của cá nhân, tổ chức về quy định hành chính.',
        isCurrentActive: true,
        totalSteps: 4,
        slaDays: 15,
        lanesCount: 2,
        formsCount: 2,
        changes: [
          {
            type: 'add',
            title: 'Quy trình tiếp nhận đa kênh',
            description: 'Tiếp nhận trực tiếp tại Một cửa, qua Cổng Dịch vụ công Quốc gia và phản ánh hiện trường.',
            target: 'Bước STEP-KNPA-01',
          },
        ],
      },
    ],
  },
  {
    id: 'wf-tranh-chap-01',
    code: 'QT-TC-2026-004',
    name: 'Quy trình hòa giải tranh chấp đất đai tại cấp xã',
    loaiDonId: 'tranh-chap',
    loaiDonName: 'Tranh chấp đất đai',
    version: 'v1.0',
    status: 'draft',
    isLatestForLoaiDon: true,
    description: 'Quy trình tổ chức hòa giải tranh chấp đất đai tại UBND cấp xã/phường theo Luật Đất đai 2024.',
    updatedAt: '18/09/2026 14:00',
    updatedBy: 'Hoàng Thị Hằng (Chuyên viên)',
    lanes: [
      { id: 'l-vt', name: 'Văn thư', code: 'VT', order: 1 },
      { id: 'l-cm', name: 'Địa chính - Xây dựng', code: 'DC', order: 2 },
      { id: 'l-ld', name: 'Lãnh đạo UBND', code: 'LD', order: 3 },
    ],
    stages: [
      { id: 'stg-1', name: 'Tiếp nhận', order: 1 },
      { id: 'stg-2', name: 'Kiểm tra hiện trạng', order: 2 },
      { id: 'stg-3', name: 'Tổ chức hòa giải', order: 3 },
    ],
    steps: [
      {
        id: 's-tc-1',
        code: 'STEP-TC-01',
        name: 'Tiếp nhận đơn tranh chấp',
        laneId: 'l-vt',
        stageId: 'stg-1',
        isStart: true,
        isEnd: false,
        timeLimitDays: 3,
        workHours: 24,
        warningBeforeHours: 4,
        workSchedule: 'Giờ hành chính',
        storedDocuments: ['Đơn yêu cầu hòa giải tranh chấp đất đai'],
        stepForms: ['BM-DC-01'],
        statusChangeDoc: 'Biên nhận tiếp nhận hồ sơ',
      },
      {
        id: 's-tc-2',
        code: 'STEP-TC-02',
        name: 'Xác minh hiện trạng ranh giới thửa đất',
        laneId: 'l-cm',
        stageId: 'stg-2',
        isStart: false,
        isEnd: false,
        timeLimitDays: 15,
        workHours: 120,
        warningBeforeHours: 16,
        workSchedule: 'Giờ hành chính',
        storedDocuments: ['Sơ đồ trích lục thửa đất', 'Biên bản kiểm tra hiện trạng'],
        stepForms: ['BM-DC-02'],
        statusChangeDoc: 'Báo cáo nguồn gốc đất đai',
      },
      {
        id: 's-tc-3',
        code: 'STEP-TC-03',
        name: 'Hội đồng hòa giải và lập biên bản',
        laneId: 'l-ld',
        stageId: 'stg-3',
        isStart: false,
        isEnd: true,
        timeLimitDays: 10,
        workHours: 80,
        warningBeforeHours: 8,
        workSchedule: 'Giờ hành chính',
        storedDocuments: ['Biên bản hòa giải thành/không thành'],
        stepForms: ['BM-DC-03'],
        statusChangeDoc: 'Biên bản hòa giải đất đai chính thức',
      },
    ],
    transitions: [
      {
        id: 'tr-tc-1',
        actionName: 'Chuyển thẩm tra thực địa',
        fromStepId: 's-tc-1',
        toStepId: 's-tc-2',
        type: 'normal',
        allowedRoles: ['Văn thư'],
        createNextTask: true,
        taskAssigneeRole: 'Địa chính',
        conditions: [],
      },
      {
        id: 'tr-tc-2',
        actionName: 'Lập hội đồng hòa giải',
        fromStepId: 's-tc-2',
        toStepId: 's-tc-3',
        type: 'normal',
        allowedRoles: ['Địa chính'],
        createNextTask: true,
        taskAssigneeRole: 'Lãnh đạo UBND',
        conditions: [],
      },
    ],
    versionHistory: [
      {
        version: 'v1.0',
        publishedAt: 'Bản nháp',
        publishedBy: 'Hoàng Thị Hằng',
        notes: 'Khởi tạo quy trình hòa giải theo Luật Đất đai 2024.',
        isCurrentActive: true,
      },
    ],
  },
  {
    id: 'wf-nac-danh-01',
    code: 'QT-ND-2025-099',
    name: 'Quy trình xử lý đơn thư không rõ họ tên, nặc danh',
    loaiDonId: 'khac',
    loaiDonName: 'Đơn khác / Nặc danh',
    version: 'v1.0',
    status: 'archived',
    description: 'Quy trình sàng lọc đơn nặc danh, không có căn cứ theo Thông tư 05/2021/TT-TTCP (Đã thay thế bởi quy trình thống nhất 2026).',
    updatedAt: '10/01/2026 08:30',
    updatedBy: 'Lê Văn Tuấn',
    effectiveDate: '01/01/2025',
    lanes: [
      { id: 'l-vt1', name: 'Văn thư', code: 'VT', order: 1 },
      { id: 'l-ld1', name: 'Lãnh đạo', code: 'LD', order: 2 },
    ],
    stages: [
      { id: 'st1', name: 'Sàng lọc', order: 1 },
      { id: 'st2', name: 'Xếp lưu', order: 2 },
    ],
    steps: [
      {
        id: 's-nd-1',
        code: 'STEP-ND-01',
        name: 'Tiếp nhận và phát hiện nặc danh',
        laneId: 'l-vt1',
        stageId: 'st1',
        isStart: true,
        isEnd: false,
        timeLimitDays: 1,
        workHours: 8,
        warningBeforeHours: 2,
        workSchedule: 'Giờ hành chính',
        storedDocuments: [],
        stepForms: [],
        statusChangeDoc: '',
      },
      {
        id: 's-nd-2',
        code: 'STEP-ND-02',
        name: 'Trình lãnh đạo phê duyệt xếp lưu',
        laneId: 'l-ld1',
        stageId: 'st2',
        isStart: false,
        isEnd: true,
        timeLimitDays: 1,
        workHours: 8,
        warningBeforeHours: 2,
        workSchedule: 'Giờ hành chính',
        storedDocuments: [],
        stepForms: [],
        statusChangeDoc: '',
      },
    ],
    transitions: [
      {
        id: 'tr-nd-1',
        actionName: 'Chuyển xếp lưu',
        fromStepId: 's-nd-1',
        toStepId: 's-nd-2',
        type: 'normal',
        allowedRoles: ['Văn thư'],
        createNextTask: false,
        taskAssigneeRole: 'Lãnh đạo',
        conditions: [],
      },
    ],
    versionHistory: [
      {
        version: 'v1.0',
        publishedAt: '01/01/2025',
        publishedBy: 'Lê Văn Tuấn',
        notes: 'Ngừng áp dụng từ tháng 01/2026 để gộp vào hệ thống GOVEX mới.',
        isCurrentActive: false,
      },
    ],
  },
];

export const CONDITION_SOURCES = [
  { id: 'ho_so', label: 'Dữ liệu hồ sơ' },
  { id: 'loai_don', label: 'Loại đơn' },
  { id: 'trang_thai', label: 'Trạng thái' },
  { id: 'tham_quyen', label: 'Thẩm quyền' },
  { id: 'van_ban', label: 'Văn bản' },
  { id: 'bieu_mau', label: 'Biểu mẫu' },
  { id: 'ket_qua', label: 'Kết quả bước trước' },
  { id: 'vai_tro', label: 'Quyền / vai trò' },
] as const;

export const CONDITION_OPERATORS = [
  { id: '=', label: '= (Bằng)' },
  { id: '≠', label: '≠ (Khác)' },
  { id: 'co_gia_tri', label: 'Có giá trị' },
  { id: 'khong_co_gia_tri', label: 'Không có giá trị' },
  { id: 'thuoc_danh_sach', label: 'Thuộc danh sách' },
  { id: 'khong_thuoc_danh_sach', label: 'Không thuộc danh sách' },
] as const;
