// src/constants/quanLyTrinhKyData.ts
import { LuotTrinhKy } from '../types/quanLyTrinhKy';

export const INITIAL_QUAN_LY_TRINH_KY: LuotTrinhKy[] = [
  {
    id: 'LTK-2026-0042',
    doiTuongTrinh: 'van_ban',
    tenDoiTuong: 'Phiếu đề xuất thụ lý và Kế hoạch xác minh đơn tố cáo sai phạm trật tự xây dựng',
    soLuongTaiLieu: 1,
    maHoSoLienQuan: 'Đ-2026-00125',
    tieuDeDon: 'Tố giác sai phạm trật tự xây dựng & lấn chiếm lối đi chung tại ngõ 128 Đội Cấn',
    stepQuyTrinhId: 'tn-2',
    tenStepQuyTrinh: 'Bước 2: Phân loại, kiểm tra điều kiện & Báo cáo đề xuất',
    nguoiTao: 'Đại úy Nguyễn Văn An',
    chucVuNguoiTao: 'Cán bộ thụ lý - Tổ xác minh 1',
    nguoiTrinh: 'Đại úy Nguyễn Văn An',
    chucVuNguoiTrinh: 'Cán bộ thụ lý - Tổ xác minh 1',
    donViTrinh: 'Đội Cảnh sát Điều tra tổng hợp - Công an quận',
    thoiGianTao: '10/03/2026 14:30',
    thoiGianTrinh: '12/03/2026 10:15',
    noiDungYeuCau:
      'Kính trình Chỉ huy Đội và Lãnh đạo Công an quận phê duyệt Kế hoạch xác minh số 42/KH-XM và Quyết định thụ lý đơn tố cáo theo quy định Luật Tố cáo 2018.',
    status: 'da_ky_va_phe_duyet',
    mucDoUuTien: 'khan',
    hanXuLy: '15/03/2026',
    kieuTrinh: 'dong_thoi',
    hanhDongYeuCauChung: 'ky_va_phe_duyet',
    luotTrinhNumber: 2,
    tongSoLuotTrinh: 2,
    danhSachTaiLieu: [
      {
        id: 'doc-42-01',
        tenTaiLieu: 'Kế hoạch xác minh đơn tố cáo số 42/KH-XM-CSĐT (Bản hoàn thiện)',
        loaiTaiLieu: 'Kế hoạch xác minh',
        soKyHieu: '42/KH-XM-CSĐT',
        nguoiSoan: 'Đại úy Nguyễn Văn An',
        ngayTao: '12/03/2026 09:30',
        phienBan: 'v2.0',
        dungLuong: '2.4 MB',
        yeuCauXuLy: 'ky_va_phe_duyet',
        trangThaiXuLy: 'da_phe_duyet',
        chuKySo: {
          nguoiKy: 'Thượng tá Phạm Đình Trọng',
          chucVu: 'Phó Thủ trưởng Cơ quan CSĐT',
          coQuan: 'Công an quận Ba Đình',
          thoiGianKy: '13/03/2026 14:00',
          loaiChungThu: 'VGCA - Ban Cơ yếu Chính phủ',
          soSeri: '5404 8892 1102 9931',
          tinhTrangHieuLuc: true,
        },
        noiDungTrichYeu:
          'Kế hoạch phối hợp với UBND phường Đội Cấn kiểm tra hiện trạng công trình vi phạm số 128 ngõ Đội Cấn, đo vẽ trích lục địa chính và thu thập lời khai các bên.',
        noiDungChiTiet: `CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM\nĐộc lập - Tự do - Hạnh phúc\n\nKẾ HOẠCH XÁC MINH NỘI DUNG TỐ CÁO\nSố: 42/KH-XM-CSĐT\n\nCăn cứ Luật Tố cáo năm 2018;\nCăn cứ Thông tư liên tịch số 01/2021/TTLT-BCA-BQP-BTC-BNN&PTNT-VKSNDTC;\nCăn cứ kết quả kiểm tra xác minh sơ bộ đơn của công dân Đ-2026-00125;\n\nI. MỤC ĐÍCH, YÊU CẦU\n1. Làm rõ hành vi xây dựng sai phép vượt tầng và chiếm dụng phần diện tích ngõ đi chung của hộ gia đình ông Trần Đình B.\n2. Thu thập đầy đủ hồ sơ địa chính, giấy phép xây dựng số 88/GPXD-UBND do UBND quận cấp ngày 14/08/2024.\n3. Đảm bảo đúng thời hạn xác minh 15 ngày làm việc theo Luật Tố cáo.\n\nII. THÀNH PHẦN TỔ XÁC MINH\n1. Đồng chí Đại úy Nguyễn Văn An - Tổ trưởng\n2. Đồng chí Thượng úy Lê Hoàng Minh - Thành viên\n3. Mời đại diện Phòng QLĐT quận và Địa chính UBND phường phối hợp kiểm tra hiện trường.`,
      },
    ],
    danhSachNguoiNhan: [
      {
        id: 'ld-42-01',
        hoTen: 'Thượng tá Trần Tuấn Nghĩa',
        chucVu: 'Phó Trưởng Công an quận',
        phongBan: 'Chỉ huy phụ trách Cảnh sát',
        avatarBg: 'bg-blue-700',
        thuTu: 1,
        kieuTrinh: 'dong_thoi',
        hanhDongYeuCau: 'ky',
        trangThai: 'da_ky',
        thoiDiemNhan: '12/03/2026 10:20',
        thoiDiemXuLy: '13/03/2026 09:15',
        yKien: 'Đồng ý kế hoạch xác minh. Đề nghị phối hợp chặt chẽ với Địa chính phường tránh khiếu kiện kéo dài.',
        chuKySo: {
          nguoiKy: 'Thượng tá Trần Tuấn Nghĩa',
          chucVu: 'Phó Trưởng Công an quận',
          coQuan: 'Công an quận Ba Đình',
          thoiGianKy: '13/03/2026 09:15',
          loaiChungThu: 'Viettel-CA Cloud PKI',
          soSeri: '7721 9918 3341 0022',
          tinhTrangHieuLuc: true,
        },
      },
      {
        id: 'ld-42-02',
        hoTen: 'Thượng tá Phạm Đình Trọng',
        chucVu: 'Phó Thủ trưởng Cơ quan CSĐT',
        phongBan: 'Thủ trưởng trực tiếp duyệt án',
        avatarBg: 'bg-emerald-700',
        thuTu: 1,
        kieuTrinh: 'dong_thoi',
        hanhDongYeuCau: 'phe_duyet',
        trangThai: 'da_phe_duyet',
        thoiDiemNhan: '12/03/2026 10:20',
        thoiDiemXuLy: '13/03/2026 14:00',
        yKien: 'Phê duyệt Kế hoạch 42/KH-XM. Giao Đội CSĐTTH triển khai đúng tiến độ và báo cáo trước ngày 25/03/2026.',
        chuKySo: {
          nguoiKy: 'Thượng tá Phạm Đình Trọng',
          chucVu: 'Phó Thủ trưởng Cơ quan CSĐT',
          coQuan: 'Công an quận Ba Đình',
          thoiGianKy: '13/03/2026 14:00',
          loaiChungThu: 'VGCA - Ban Cơ yếu Chính phủ',
          soSeri: '5404 8892 1102 9931',
          tinhTrangHieuLuc: true,
        },
      },
    ],
    lichSuXuLy: [
      {
        id: 'log-42-06',
        thoiGian: '13/03/2026 14:00',
        nguoiThucHien: 'Thượng tá Phạm Đình Trọng',
        chucVu: 'Phó Thủ trưởng Cơ quan CSĐT',
        hanhDong: 'Đã phê duyệt & Ký số CA',
        noiDungYKien: 'Phê duyệt Kế hoạch 42/KH-XM. Giao Đội CSĐTTH triển khai đúng tiến độ.',
        phienBanXuLy: 'v2.0',
        luotTrinhIndex: 2,
      },
      {
        id: 'log-42-05',
        thoiGian: '13/03/2026 09:15',
        nguoiThucHien: 'Thượng tá Trần Tuấn Nghĩa',
        chucVu: 'Phó Trưởng Công an quận',
        hanhDong: 'Đã ký nháy chuyên môn',
        noiDungYKien: 'Đồng ý kế hoạch xác minh. Đề nghị phối hợp địa chính phường đo vẽ kỹ lưỡng.',
        phienBanXuLy: 'v2.0',
        luotTrinhIndex: 2,
      },
      {
        id: 'log-42-04',
        thoiGian: '12/03/2026 10:15',
        nguoiThucHien: 'Đại úy Nguyễn Văn An',
        chucVu: 'Cán bộ thụ lý',
        hanhDong: 'Trình lại (Lượt mới)',
        noiDungYKien: 'Đã bổ sung bản đồ địa chính trích lục theo đúng chỉ đạo tại Lượt 1 và gửi trình song song 02 lãnh đạo.',
        phienBanXuLy: 'v2.0',
        luotTrinhIndex: 2,
      },
      {
        id: 'log-42-03',
        thoiGian: '11/03/2026 16:45',
        nguoiThucHien: 'Thượng tá Phạm Đình Trọng',
        chucVu: 'Phó Thủ trưởng CQĐT',
        hanhDong: 'Đã trả lại lượt trình',
        noiDungYKien: 'Kế hoạch v1.0 còn thiếu trích lục bản đồ địa chính ngõ 128 Đội Cấn. Yêu cầu phối hợp địa chính phường đo vẽ bổ sung trước khi duyệt.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
      {
        id: 'log-42-02',
        thoiGian: '11/03/2026 09:30',
        nguoiThucHien: 'Đại úy Nguyễn Văn An',
        chucVu: 'Cán bộ thụ lý',
        hanhDong: 'Trình văn bản / hồ sơ',
        noiDungYKien: 'Kính trình Lãnh đạo phê duyệt Kế hoạch xác minh ban đầu.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
      {
        id: 'log-42-01',
        thoiGian: '10/03/2026 14:30',
        nguoiThucHien: 'Đại úy Nguyễn Văn An',
        chucVu: 'Cán bộ thụ lý',
        hanhDong: 'Tạo lượt trình',
        noiDungYKien: 'Khởi tạo hồ sơ trình Kế hoạch xác minh số 42/KH-XM.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
    ],
  },

  {
    id: 'LTK-2026-0048',
    doiTuongTrinh: 'tep_ho_so',
    tenDoiTuong: 'Tệp hồ sơ kiểm tra hiện trường & đo đạc hiện trạng vi phạm trật tự xây dựng',
    soLuongTaiLieu: 4,
    maHoSoLienQuan: 'Đ-2026-00125',
    tieuDeDon: 'Tố giác sai phạm trật tự xây dựng & lấn chiếm lối đi chung tại ngõ 128 Đội Cấn',
    stepQuyTrinhId: 'tl-1',
    tenStepQuyTrinh: 'Bước 4: Xác minh thực tế & Thu thập tài liệu chứng cứ',
    nguoiTao: 'Đại úy Nguyễn Văn An',
    chucVuNguoiTao: 'Cán bộ thụ lý',
    nguoiTrinh: 'Đại úy Nguyễn Văn An',
    chucVuNguoiTrinh: 'Cán bộ thụ lý',
    donViTrinh: 'Đội CSĐT Tổng hợp',
    thoiGianTao: '14/03/2026 11:00',
    thoiGianTrinh: '14/03/2026 16:30',
    noiDungYeuCau:
      'Kính trình Đồng chí Chỉ huy Đội và Lãnh đạo Công an quận phê duyệt Báo cáo kết quả kiểm tra thực địa, làm cơ sở chuyển hồ sơ đề xuất UBND quận xử lý vi phạm hành chính.',
    status: 'dang_cho_xu_ly',
    mucDoUuTien: 'thuong',
    hanXuLy: '18/03/2026',
    kieuTrinh: 'tuan_tu',
    hanhDongYeuCauChung: 'ky_va_phe_duyet',
    luotTrinhNumber: 1,
    tongSoLuotTrinh: 1,
    danhSachTaiLieu: [
      {
        id: 'doc-48-01',
        tenTaiLieu: 'Biên bản kiểm tra hiện trường vi phạm xây dựng ngõ 128 Đội Cấn',
        loaiTaiLieu: 'Biên bản kiểm tra',
        soKyHieu: '14/BB-KTHT',
        nguoiSoan: 'Đại úy Nguyễn Văn An',
        ngayTao: '14/03/2026 10:00',
        phienBan: 'v1.0',
        dungLuong: '1.8 MB',
        yeuCauXuLy: 'ky',
        trangThaiXuLy: 'chua_xu_ly',
        noiDungTrichYeu: 'Biên bản lập hồi 09h00 ngày 14/03/2026 có sự tham gia của Địa chính phường, TDP số 3 và chủ hộ vi phạm.',
        noiDungChiTiet: 'Biên bản ghi nhận diện tích lấn chiếm ngõ đi chung là 1.85m bề ngang, chiều dài 4.2m. Kết cấu xây gạch chịu lực kiên cố.',
      },
      {
        id: 'doc-48-02',
        tenTaiLieu: 'Báo cáo đề xuất hướng xử lý vi phạm đất đai và trật tự xây dựng',
        loaiTaiLieu: 'Báo cáo đề xuất',
        soKyHieu: '18/BC-ĐX',
        nguoiSoan: 'Đại úy Nguyễn Văn An',
        ngayTao: '14/03/2026 14:00',
        phienBan: 'v1.0',
        dungLuong: '2.1 MB',
        yeuCauXuLy: 'phe_duyet',
        trangThaiXuLy: 'chua_xu_ly',
        noiDungTrichYeu: 'Đề xuất kiến nghị UBND quận Ba Đình ban hành Quyết định áp dụng biện pháp khắc phục hậu quả buộc phá dỡ.',
      },
      {
        id: 'doc-48-03',
        tenTaiLieu: 'Sơ đồ trích lục đo vẽ địa chính ngõ 128 Đội Cấn (Bản vẽ kỹ thuật CAD)',
        loaiTaiLieu: 'Bản vẽ kỹ thuật',
        soKyHieu: 'TL-128/DC',
        nguoiSoan: 'Cán bộ Địa chính phường',
        ngayTao: '13/03/2026 16:30',
        phienBan: 'v1.0',
        dungLuong: '8.4 MB',
        yeuCauXuLy: 'tham_khao',
        trangThaiXuLy: 'khong_ap_dung',
        noiDungTrichYeu: 'Bản vẽ thể hiện mốc giới sử dụng đất theo Giấy chứng nhận quyền sử dụng đất năm 2004 đối chiếu hiện trạng 2026.',
      },
      {
        id: 'doc-48-04',
        tenTaiLieu: 'Bảng ảnh hiện trường chụp vi phạm trật tự xây dựng (12 góc chụp)',
        loaiTaiLieu: 'Ảnh hiện trường',
        nguoiSoan: 'Tổ xác minh CSĐT',
        ngayTao: '14/03/2026 10:30',
        phienBan: 'v1.0',
        dungLuong: '14.2 MB',
        yeuCauXuLy: 'tham_khao',
        trangThaiXuLy: 'khong_ap_dung',
        noiDungTrichYeu: 'Tập hợp ảnh chụp toàn cảnh, mốc ranh giới lối đi chung và phần mái vẩy bê tông cơi nới.',
      },
    ],
    danhSachNguoiNhan: [
      {
        id: 'ld-48-01',
        hoTen: 'Thiếu tá Vũ Hoàng Long',
        chucVu: 'Đội trưởng Đội CSĐT Tổng hợp',
        phongBan: 'Chỉ huy Đội CSĐTTH',
        avatarBg: 'bg-indigo-700',
        thuTu: 1,
        kieuTrinh: 'tuan_tu',
        hanhDongYeuCau: 'ky',
        trangThai: 'dang_cho_xu_ly',
        thoiDiemNhan: '14/03/2026 16:30',
      },
      {
        id: 'ld-48-02',
        hoTen: 'Thượng tá Phạm Đình Trọng',
        chucVu: 'Phó Thủ trưởng Cơ quan CSĐT',
        phongBan: 'Lãnh đạo Cơ quan CSĐT',
        avatarBg: 'bg-emerald-700',
        thuTu: 2,
        kieuTrinh: 'tuan_tu',
        hanhDongYeuCau: 'phe_duyet',
        trangThai: 'chua_den_luot',
      },
    ],
    lichSuXuLy: [
      {
        id: 'log-48-02',
        thoiGian: '14/03/2026 16:30',
        nguoiThucHien: 'Đại úy Nguyễn Văn An',
        chucVu: 'Cán bộ thụ lý',
        hanhDong: 'Trình văn bản / hồ sơ',
        noiDungYKien: 'Trình tuần tự Đội trưởng ký duyệt trước khi chuyển Thủ trưởng CQĐT phê duyệt.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
      {
        id: 'log-48-01',
        thoiGian: '14/03/2026 11:00',
        nguoiThucHien: 'Đại úy Nguyễn Văn An',
        chucVu: 'Cán bộ thụ lý',
        hanhDong: 'Tạo lượt trình',
        noiDungYKien: 'Khởi tạo tệp hồ sơ kiểm tra thực địa gồm 4 tài liệu.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
    ],
  },

  {
    id: 'LTK-2026-0039',
    doiTuongTrinh: 'van_ban',
    tenDoiTuong: 'Quyết định thụ lý tố cáo số 15/QĐ-CATP và Thông báo thụ lý',
    soLuongTaiLieu: 1,
    maHoSoLienQuan: 'Đ-2026-00088',
    tieuDeDon: 'Tố cáo hành vi bao che lấn chiếm đất công tại khu dân cư An Phú',
    stepQuyTrinhId: 'tl-2',
    tenStepQuyTrinh: 'Bước 3: Ban hành Quyết định thụ lý tố cáo',
    nguoiTao: 'Trung tá Lê Minh Tuấn',
    chucVuNguoiTao: 'Điều tra viên',
    nguoiTrinh: 'Trung tá Lê Minh Tuấn',
    chucVuNguoiTrinh: 'Điều tra viên',
    donViTrinh: 'Phòng Cảnh sát Kinh tế - CATP',
    thoiGianTao: '08/03/2026 09:00',
    thoiGianTrinh: '08/03/2026 15:00',
    noiDungYeuCau: 'Trình duyệt Quyết định thụ lý giải quyết tố cáo theo thẩm quyền quy định tại Điều 29 Luật Tố cáo 2018.',
    status: 'dang_xu_ly_mot_phan',
    mucDoUuTien: 'khan',
    hanXuLy: '12/03/2026',
    kieuTrinh: 'tuan_tu',
    hanhDongYeuCauChung: 'ky_va_phe_duyet',
    luotTrinhNumber: 1,
    tongSoLuotTrinh: 1,
    danhSachTaiLieu: [
      {
        id: 'doc-39-01',
        tenTaiLieu: 'Quyết định thụ lý tố cáo số 15/QĐ-CATP',
        loaiTaiLieu: 'Quyết định hành chính',
        soKyHieu: '15/QĐ-CATP',
        nguoiSoan: 'Trung tá Lê Minh Tuấn',
        ngayTao: '08/03/2026 09:00',
        phienBan: 'v1.0',
        dungLuong: '1.2 MB',
        yeuCauXuLy: 'ky_va_phe_duyet',
        trangThaiXuLy: 'da_ky',
        chuKySo: {
          nguoiKy: 'Thiếu tá Vũ Hoàng Long',
          chucVu: 'Đội trưởng Đội CSĐTTH',
          coQuan: 'Công an quận Ba Đình',
          thoiGianKy: '09/03/2026 09:40',
          loaiChungThu: 'Viettel-CA Cloud PKI',
          soSeri: '6618 1029 4432 0019',
          tinhTrangHieuLuc: true,
        },
        noiDungTrichYeu: 'Thụ lý giải quyết tố cáo đối với hành vi lợi dụng chức vụ trong việc xác nhận nguồn gốc đất tại TDP An Phú.',
      },
    ],
    danhSachNguoiNhan: [
      {
        id: 'ld-39-01',
        hoTen: 'Thiếu tá Vũ Hoàng Long',
        chucVu: 'Đội trưởng Đội CSĐTTH',
        phongBan: 'Chỉ huy Đội',
        avatarBg: 'bg-indigo-700',
        thuTu: 1,
        kieuTrinh: 'tuan_tu',
        hanhDongYeuCau: 'ky',
        trangThai: 'da_ky',
        thoiDiemNhan: '08/03/2026 15:00',
        thoiDiemXuLy: '09/03/2026 09:40',
        yKien: 'Đã kiểm tra hồ sơ, đủ điều kiện thụ lý tố cáo. Đề nghị đồng chí Thượng tá Phạm Đình Trọng xem xét ký duyệt ban hành.',
        chuKySo: {
          nguoiKy: 'Thiếu tá Vũ Hoàng Long',
          chucVu: 'Đội trưởng Đội CSĐTTH',
          coQuan: 'Công an quận Ba Đình',
          thoiGianKy: '09/03/2026 09:40',
          loaiChungThu: 'Viettel-CA Cloud PKI',
          soSeri: '6618 1029 4432 0019',
          tinhTrangHieuLuc: true,
        },
      },
      {
        id: 'ld-39-02',
        hoTen: 'Thượng tá Phạm Đình Trọng',
        chucVu: 'Phó Thủ trưởng Cơ quan CSĐT',
        phongBan: 'Thủ trưởng phê duyệt',
        avatarBg: 'bg-emerald-700',
        thuTu: 2,
        kieuTrinh: 'tuan_tu',
        hanhDongYeuCau: 'phe_duyet',
        trangThai: 'dang_cho_xu_ly',
        thoiDiemNhan: '09/03/2026 09:45',
      },
    ],
    lichSuXuLy: [
      {
        id: 'log-39-03',
        thoiGian: '09/03/2026 09:45',
        nguoiThucHien: 'Hệ thống tự động',
        chucVu: 'Workflow Engine',
        hanhDong: 'Tiếp nhận xử lý',
        noiDungYKien: 'Đã chuyển tiếp lượt trình đến Thượng tá Phạm Đình Trọng (Thứ tự 2 trong luồng tuần tự).',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
      {
        id: 'log-39-02',
        thoiGian: '09/03/2026 09:40',
        nguoiThucHien: 'Thiếu tá Vũ Hoàng Long',
        chucVu: 'Đội trưởng',
        hanhDong: 'Đã ký nháy chuyên môn',
        noiDungYKien: 'Đồng ý thụ lý. Đề nghị Lãnh đạo ký duyệt.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
      {
        id: 'log-39-01',
        thoiGian: '08/03/2026 15:00',
        nguoiThucHien: 'Trung tá Lê Minh Tuấn',
        chucVu: 'Điều tra viên',
        hanhDong: 'Trình văn bản / hồ sơ',
        noiDungYKien: 'Kính trình Lãnh đạo xem xét phê duyệt Quyết định thụ lý số 15/QĐ-CATP.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
    ],
  },

  {
    id: 'LTK-2026-0035',
    doiTuongTrinh: 'tep_ho_so',
    tenDoiTuong: 'Tệp hồ sơ bàn giao tin báo tội phạm lừa đảo chiếm đoạt tài sản sang CQĐT cấp tỉnh',
    soLuongTaiLieu: 3,
    maHoSoLienQuan: 'Đ-2026-00045',
    tieuDeDon: 'Tố giác hành vi lừa đảo thông qua huy động vốn đầu tư bất động sản',
    stepQuyTrinhId: 'tg-8',
    tenStepQuyTrinh: 'Bước 8: Bàn giao chuyển tiếp sang Cơ quan CSĐT có thẩm quyền',
    nguoiTao: 'Đại úy Trần Kim Chi',
    chucVuNguoiTao: 'Cán bộ tổng hợp',
    nguoiTrinh: 'Đại úy Trần Kim Chi',
    chucVuNguoiTrinh: 'Cán bộ tổng hợp',
    donViTrinh: 'Đội Cảnh sát Hình sự',
    thoiGianTao: '04/03/2026 08:30',
    thoiGianTrinh: '05/03/2026 14:00',
    noiDungYeuCau: 'Trình hồ sơ bàn giao vật chứng và hồ sơ tin báo tội phạm vượt thẩm quyền cấp quận.',
    status: 'da_tra_lai',
    mucDoUuTien: 'hoa_toc',
    hanXuLy: '07/03/2026',
    kieuTrinh: 'tuan_tu',
    hanhDongYeuCauChung: 'phe_duyet',
    luotTrinhNumber: 1,
    tongSoLuotTrinh: 1,
    lyDoTraLai: 'Hồ sơ thiếu biên lai xác nhận niêm phong 14 tập hợp đồng ủy thác gốc và chưa có bản dịch công chứng sao kê nước ngoài.',
    danhSachTaiLieu: [
      {
        id: 'doc-35-01',
        tenTaiLieu: 'Biên bản bàn giao hồ sơ vụ việc sang Phòng CSHS - CATP',
        loaiTaiLieu: 'Biên bản bàn giao',
        soKyHieu: '09/BB-BG',
        nguoiSoan: 'Đại úy Trần Kim Chi',
        ngayTao: '04/03/2026 08:30',
        phienBan: 'v1.0',
        dungLuong: '1.5 MB',
        yeuCauXuLy: 'phe_duyet',
        trangThaiXuLy: 'chua_xu_ly',
        noiDungTrichYeu: 'Bàn giao 14 tập hồ sơ sao kê tài khoản ngân hàng và đơn tố giác của 18 công dân.',
      },
      {
        id: 'doc-35-02',
        tenTaiLieu: 'Báo cáo tổng kết xác minh nguồn tin số 12/BC-CSHS',
        loaiTaiLieu: 'Báo cáo xác minh',
        soKyHieu: '12/BC-CSHS',
        nguoiSoan: 'Đại úy Trần Kim Chi',
        ngayTao: '04/03/2026 10:00',
        phienBan: 'v1.0',
        dungLuong: '3.4 MB',
        yeuCauXuLy: 'phe_duyet',
        trangThaiXuLy: 'chua_xu_ly',
      },
      {
        id: 'doc-35-03',
        tenTaiLieu: 'Bảng kê chi tiết vật chứng, tài liệu niêm phong',
        loaiTaiLieu: 'Bảng kê vật chứng',
        nguoiSoan: 'Tổ lưu trữ vật chứng',
        ngayTao: '04/03/2026 11:30',
        phienBan: 'v1.0',
        dungLuong: '900 KB',
        yeuCauXuLy: 'tham_khao',
        trangThaiXuLy: 'khong_ap_dung',
      },
    ],
    danhSachNguoiNhan: [
      {
        id: 'ld-35-01',
        hoTen: 'Thượng tá Phạm Đình Trọng',
        chucVu: 'Phó Thủ trưởng Cơ quan CSĐT',
        phongBan: 'Lãnh đạo Cơ quan CSĐT',
        avatarBg: 'bg-emerald-700',
        thuTu: 1,
        kieuTrinh: 'tuan_tu',
        hanhDongYeuCau: 'phe_duyet',
        trangThai: 'da_tra_lai',
        thoiDiemNhan: '05/03/2026 14:00',
        thoiDiemXuLy: '06/03/2026 11:20',
        yKien: 'Trả lại hồ sơ để Tổ công tác niêm phong lại toàn bộ hợp đồng gốc và bổ sung lời khai của người bảo lãnh.',
      },
    ],
    lichSuXuLy: [
      {
        id: 'log-35-02',
        thoiGian: '06/03/2026 11:20',
        nguoiThucHien: 'Thượng tá Phạm Đình Trọng',
        chucVu: 'Phó Thủ trưởng Cơ quan CSĐT',
        hanhDong: 'Đã trả lại lượt trình',
        noiDungYKien: 'Trả lại hồ sơ để Tổ công tác niêm phong lại toàn bộ hợp đồng gốc và bổ sung lời khai của người bảo lãnh.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
      {
        id: 'log-35-01',
        thoiGian: '05/03/2026 14:00',
        nguoiThucHien: 'Đại úy Trần Kim Chi',
        chucVu: 'Cán bộ tổng hợp',
        hanhDong: 'Trình văn bản / hồ sơ',
        noiDungYKien: 'Kính trình Lãnh đạo ký duyệt Bàn giao chuyển CQĐT cấp tỉnh.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
    ],
  },

  {
    id: 'LTK-2026-0028',
    doiTuongTrinh: 'van_ban',
    tenDoiTuong: 'Kế hoạch xác minh tố cáo cán bộ vi phạm trật tự xây dựng và quản lý đất đai',
    soLuongTaiLieu: 1,
    maHoSoLienQuan: 'Đ-2025-0105',
    tieuDeDon: 'Tố cáo hành vi vi phạm trật tự xây dựng và quản lý đất đai',
    stepQuyTrinhId: 'tl-1',
    tenStepQuyTrinh: 'Bước 2: Lập Kế hoạch xác minh tố cáo',
    nguoiTao: 'Nguyễn Minh Anh',
    chucVuNguoiTao: 'Chuyên viên xử lý đơn',
    nguoiTrinh: 'Nguyễn Minh Anh',
    chucVuNguoiTrinh: 'Chuyên viên xử lý đơn',
    donViTrinh: 'Phòng Tiếp công dân & Xử lý đơn',
    thoiGianTao: '28/02/2026 09:15',
    thoiGianTrinh: '28/02/2026 16:00',
    noiDungYeuCau: 'Trình Kế hoạch xác minh thực địa đối với đơn tố cáo của bà Vũ Thị Thanh.',
    status: 'da_ky',
    mucDoUuTien: 'thuong',
    hanXuLy: '05/03/2026',
    kieuTrinh: 'tuan_tu',
    hanhDongYeuCauChung: 'ky',
    luotTrinhNumber: 1,
    tongSoLuotTrinh: 1,
    danhSachTaiLieu: [
      {
        id: 'doc-28-01',
        tenTaiLieu: 'Kế hoạch xác minh thực địa số 28/KH-XM',
        loaiTaiLieu: 'Kế hoạch xác minh',
        soKyHieu: '28/KH-XM',
        nguoiSoan: 'Nguyễn Minh Anh',
        ngayTao: '28/02/2026 09:15',
        phienBan: 'v1.0',
        dungLuong: '1.6 MB',
        yeuCauXuLy: 'ky',
        trangThaiXuLy: 'da_ky',
        chuKySo: {
          nguoiKy: 'Trần Văn Hùng',
          chucVu: 'Phó Chánh Thanh tra thành phố',
          coQuan: 'Thanh tra Thành phố Hà Nội',
          thoiGianKy: '02/03/2026 10:15',
          loaiChungThu: 'Ban Cơ yếu Chính phủ',
          soSeri: '9920 1827 0031',
          tinhTrangHieuLuc: true,
        },
      },
    ],
    danhSachNguoiNhan: [
      {
        id: 'ld-28-01',
        hoTen: 'Trần Văn Hùng',
        chucVu: 'Phó Chánh Thanh tra thành phố',
        phongBan: 'Lãnh đạo Thanh tra',
        avatarBg: 'bg-emerald-700',
        thuTu: 1,
        kieuTrinh: 'tuan_tu',
        hanhDongYeuCau: 'ky',
        trangThai: 'da_ky',
        thoiDiemNhan: '28/02/2026 16:00',
        thoiDiemXuLy: '02/03/2026 10:15',
        yKien: 'Đồng ý kế hoạch. Giao Phòng Tiếp dân phối hợp Đội Thanh tra số 2 tiến hành kiểm tra thực tế.',
      },
    ],
    lichSuXuLy: [
      {
        id: 'log-28-02',
        thoiGian: '02/03/2026 10:15',
        nguoiThucHien: 'Trần Văn Hùng',
        chucVu: 'Phó Chánh Thanh tra',
        hanhDong: 'Đã ký nháy chuyên môn',
        noiDungYKien: 'Đồng ý kế hoạch xác minh.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
      {
        id: 'log-28-01',
        thoiGian: '28/02/2026 16:00',
        nguoiThucHien: 'Nguyễn Minh Anh',
        chucVu: 'Chuyên viên xử lý đơn',
        hanhDong: 'Trình văn bản / hồ sơ',
        noiDungYKien: 'Kính trình Lãnh đạo ký duyệt kế hoạch.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
    ],
  },

  {
    id: 'LTK-2026-0051',
    doiTuongTrinh: 'van_ban',
    tenDoiTuong: 'Dự thảo Thông báo kết luận nội dung tố cáo gửi người tố cáo và người bị tố cáo',
    soLuongTaiLieu: 1,
    maHoSoLienQuan: 'Đ-2026-00125',
    tieuDeDon: 'Tố giác sai phạm trật tự xây dựng & lấn chiếm lối đi chung tại ngõ 128 Đội Cấn',
    stepQuyTrinhId: 'tl-6',
    tenStepQuyTrinh: 'Bước 6: Ban hành Kết luận nội dung tố cáo',
    nguoiTao: 'Đại úy Nguyễn Văn An',
    chucVuNguoiTao: 'Cán bộ thụ lý',
    nguoiTrinh: 'Đại úy Nguyễn Văn An',
    chucVuNguoiTrinh: 'Cán bộ thụ lý',
    donViTrinh: 'Đội CSĐT Tổng hợp',
    thoiGianTao: '15/03/2026 09:30',
    thoiGianTrinh: '15/03/2026 09:30',
    noiDungYeuCau: 'Soạn thảo dự thảo Thông báo kết luận nội dung tố cáo (Bản nháp cán bộ đang biên tập).',
    status: 'ban_nhap',
    mucDoUuTien: 'thuong',
    hanXuLy: '25/03/2026',
    kieuTrinh: 'dong_thoi',
    hanhDongYeuCauChung: 'phe_duyet',
    luotTrinhNumber: 1,
    tongSoLuotTrinh: 1,
    danhSachTaiLieu: [
      {
        id: 'doc-51-01',
        tenTaiLieu: 'Dự thảo Thông báo số .../TB-KLTC về kết luận nội dung tố cáo',
        loaiTaiLieu: 'Thông báo kết luận',
        nguoiSoan: 'Đại úy Nguyễn Văn An',
        ngayTao: '15/03/2026 09:30',
        phienBan: 'v0.1',
        dungLuong: '850 KB',
        yeuCauXuLy: 'phe_duyet',
        trangThaiXuLy: 'chua_xu_ly',
        noiDungTrichYeu: 'Dự thảo tóm tắt kết quả đo đạc vi phạm và trách nhiệm tháo dỡ công trình trong 30 ngày.',
      },
    ],
    danhSachNguoiNhan: [
      {
        id: 'ld-51-01',
        hoTen: 'Thượng tá Phạm Đình Trọng',
        chucVu: 'Phó Thủ trưởng Cơ quan CSĐT',
        phongBan: 'Lãnh đạo Cơ quan CSĐT',
        avatarBg: 'bg-emerald-700',
        thuTu: 1,
        kieuTrinh: 'dong_thoi',
        hanhDongYeuCau: 'phe_duyet',
        trangThai: 'chua_den_luot',
      },
    ],
    lichSuXuLy: [
      {
        id: 'log-51-01',
        thoiGian: '15/03/2026 09:30',
        nguoiThucHien: 'Đại úy Nguyễn Văn An',
        chucVu: 'Cán bộ thụ lý',
        hanhDong: 'Tạo lượt trình',
        noiDungYKien: 'Tạo bản nháp dự thảo thông báo kết luận.',
        phienBanXuLy: 'v0.1',
        luotTrinhIndex: 1,
      },
    ],
  },

  {
    id: 'LTK-2026-0030',
    doiTuongTrinh: 'tep_ho_so',
    tenDoiTuong: 'Tệp hồ sơ đề xuất tạm đình chỉ xác minh tố cáo do vụ việc đang thụ lý tại Tòa án',
    soLuongTaiLieu: 2,
    maHoSoLienQuan: 'Đ-2026-00019',
    tieuDeDon: 'Tranh chấp ranh giới thửa đất liền kề tại tổ dân phố số 5',
    stepQuyTrinhId: 'tl-3',
    tenStepQuyTrinh: 'Bước 3: Thẩm tra điều kiện thụ lý',
    nguoiTao: 'Thượng úy Bùi Tuấn Anh',
    chucVuNguoiTao: 'Cán bộ thụ lý',
    nguoiTrinh: 'Thượng úy Bùi Tuấn Anh',
    chucVuNguoiTrinh: 'Cán bộ thụ lý',
    donViTrinh: 'Đội CSĐT Tổng hợp',
    thoiGianTao: '25/02/2026 14:00',
    thoiGianTrinh: '26/02/2026 08:30',
    noiDungYeuCau: 'Trình hồ sơ tạm đình chỉ do TAND quận đã thụ lý vụ án dân sự tranh chấp quyền sử dụng đất.',
    status: 'da_tu_choi',
    mucDoUuTien: 'thuong',
    hanXuLy: '01/03/2026',
    kieuTrinh: 'tuan_tu',
    hanhDongYeuCauChung: 'phe_duyet',
    luotTrinhNumber: 1,
    tongSoLuotTrinh: 1,
    lyDoTraLai: 'Từ chối tạm đình chỉ. Căn cứ Khoản 2 Điều 28 Luật Tố cáo, hành vi có dấu hiệu làm giả giấy chứng nhận QSDĐ thuộc thẩm quyền điều tra hình sự độc lập với án dân sự.',
    danhSachTaiLieu: [
      {
        id: 'doc-30-01',
        tenTaiLieu: 'Tờ trình đề xuất tạm đình chỉ thụ lý đơn tố cáo',
        loaiTaiLieu: 'Tờ trình',
        soKyHieu: '05/TTr-ĐX',
        nguoiSoan: 'Thượng úy Bùi Tuấn Anh',
        ngayTao: '25/02/2026 14:00',
        phienBan: 'v1.0',
        dungLuong: '1.1 MB',
        yeuCauXuLy: 'phe_duyet',
        trangThaiXuLy: 'chua_xu_ly',
      },
      {
        id: 'doc-30-02',
        tenTaiLieu: 'Thông báo thụ lý vụ án dân sự của TAND quận Ba Đình (Bản sao)',
        loaiTaiLieu: 'Văn bản Tòa án',
        nguoiSoan: 'TAND quận Ba Đình',
        ngayTao: '20/02/2026 15:00',
        phienBan: 'v1.0',
        dungLuong: '2.5 MB',
        yeuCauXuLy: 'tham_khao',
        trangThaiXuLy: 'khong_ap_dung',
      },
    ],
    danhSachNguoiNhan: [
      {
        id: 'ld-30-01',
        hoTen: 'Thượng tá Phạm Đình Trọng',
        chucVu: 'Phó Thủ trưởng Cơ quan CSĐT',
        phongBan: 'Lãnh đạo Cơ quan CSĐT',
        avatarBg: 'bg-emerald-700',
        thuTu: 1,
        kieuTrinh: 'tuan_tu',
        hanhDongYeuCau: 'phe_duyet',
        trangThai: 'tu_choi',
        thoiDiemNhan: '26/02/2026 08:30',
        thoiDiemXuLy: '27/02/2026 15:40',
        yKien: 'Không chấp thuận tạm đình chỉ. Yêu cầu tiếp tục xác minh dấu hiệu làm giả con dấu, tài liệu của cơ quan tổ chức.',
      },
    ],
    lichSuXuLy: [
      {
        id: 'log-30-02',
        thoiGian: '27/02/2026 15:40',
        nguoiThucHien: 'Thượng tá Phạm Đình Trọng',
        chucVu: 'Phó Thủ trưởng CQĐT',
        hanhDong: 'Từ chối phê duyệt',
        noiDungYKien: 'Không chấp thuận tạm đình chỉ. Yêu cầu tiếp tục xác minh dấu hiệu làm giả con dấu, tài liệu.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
      {
        id: 'log-30-01',
        thoiGian: '26/02/2026 08:30',
        nguoiThucHien: 'Thượng úy Bùi Tuấn Anh',
        chucVu: 'Cán bộ thụ lý',
        hanhDong: 'Trình văn bản / hồ sơ',
        noiDungYKien: 'Kính trình Lãnh đạo phê duyệt tờ trình tạm đình chỉ.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
    ],
  },

  {
    id: 'LTK-2026-0022',
    doiTuongTrinh: 'van_ban',
    tenDoiTuong: 'Báo cáo rà soát trùng lặp đơn khiếu nại - tố cáo lĩnh vực giải phóng mặt bằng',
    soLuongTaiLieu: 1,
    maHoSoLienQuan: 'Đ-2026-00012',
    tieuDeDon: 'Khiếu nại phương án bồi thường hỗ trợ tái định cư dự án đường vành đai',
    stepQuyTrinhId: 'tn-kt-2',
    tenStepQuyTrinh: 'Bước 1: Tra cứu trùng đơn & Lịch sử giải quyết',
    nguoiTao: 'Đại úy Nguyễn Văn An',
    chucVuNguoiTao: 'Cán bộ thụ lý',
    nguoiTrinh: 'Đại úy Nguyễn Văn An',
    chucVuNguoiTrinh: 'Cán bộ thụ lý',
    donViTrinh: 'Đội CSĐT Tổng hợp',
    thoiGianTao: '20/02/2026 10:00',
    thoiGianTrinh: '20/02/2026 14:00',
    noiDungYeuCau: 'Trình báo cáo rà soát trùng đơn gửi Lãnh đạo chỉ đạo xử lý.',
    status: 'da_thu_hoi',
    mucDoUuTien: 'thuong',
    hanXuLy: '25/02/2026',
    kieuTrinh: 'tuan_tu',
    hanhDongYeuCauChung: 'ky',
    luotTrinhNumber: 1,
    tongSoLuotTrinh: 1,
    danhSachTaiLieu: [
      {
        id: 'doc-22-01',
        tenTaiLieu: 'Báo cáo rà soát đơn trùng lặp số 04/BC-RS',
        loaiTaiLieu: 'Báo cáo rà soát',
        soKyHieu: '04/BC-RS',
        nguoiSoan: 'Đại úy Nguyễn Văn An',
        ngayTao: '20/02/2026 10:00',
        phienBan: 'v1.0',
        dungLuong: '780 KB',
        yeuCauXuLy: 'ky',
        trangThaiXuLy: 'chua_xu_ly',
      },
    ],
    danhSachNguoiNhan: [
      {
        id: 'ld-22-01',
        hoTen: 'Thiếu tá Vũ Hoàng Long',
        chucVu: 'Đội trưởng Đội CSĐTTH',
        phongBan: 'Chỉ huy Đội',
        avatarBg: 'bg-indigo-700',
        thuTu: 1,
        kieuTrinh: 'tuan_tu',
        hanhDongYeuCau: 'ky',
        trangThai: 'dang_cho_xu_ly',
        thoiDiemNhan: '20/02/2026 14:00',
      },
    ],
    lichSuXuLy: [
      {
        id: 'log-22-02',
        thoiGian: '20/02/2026 16:30',
        nguoiThucHien: 'Đại úy Nguyễn Văn An',
        chucVu: 'Cán bộ thụ lý',
        hanhDong: 'Thu hồi lượt trình',
        noiDungYKien: 'Cán bộ thụ lý chủ động thu hồi do phát hiện người dân vừa nộp bổ sung Giấy ủy quyền mới có công chứng.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
      {
        id: 'log-22-01',
        thoiGian: '20/02/2026 14:00',
        nguoiThucHien: 'Đại úy Nguyễn Văn An',
        chucVu: 'Cán bộ thụ lý',
        hanhDong: 'Trình văn bản / hồ sơ',
        noiDungYKien: 'Trình báo cáo rà soát đơn.',
        phienBanXuLy: 'v1.0',
        luotTrinhIndex: 1,
      },
    ],
  },
];
