import { WorkItem } from '../types/work';

export const INITIAL_WORK_ITEMS: WorkItem[] = [
  // ================= COLUMN 1: CẦN TÔI XỬ LÝ (4 việc) =================
  // 1. Quá hạn khẩn cấp - AI CẦN KIỂM TRA (Confidence 68%)
  {
    id: 'VV-2025-0430',
    code: 'VV-2025-0430',
    title: 'Thẩm định hồ sơ cấp phép XD ngõ 128 Đội Cấn',
    sender: 'Nguyễn Hải Phong',
    source: 'Trực tiếp Một cửa',
    timeReceived: '16/09/2026 08:00',
    priority: 'urgent',
    deadlineType: 'overdue',
    deadlineText: 'Quá hạn 2 giờ',
    deadlineFull: 'Hôm nay - 11:30',
    column: 'action_required',
    nextAction: 'Kiểm tra và xác nhận kết quả AI',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Phòng Tiếp dân & Xử lý đơn',
    },
    progress: {
      currentStep: 3,
      totalSteps: 5,
      stepName: 'Thẩm định hiện trạng',
      steps: ['Tiếp nhận', 'Kiểm tra hồ sơ', 'Thẩm định', 'Trình ký', 'Trả kết quả'],
    },
    docCount: 5,
    cta: {
      label: 'Kiểm tra',
      actionType: 'review_ai',
      variant: 'warning',
    },
    category: 'Xây dựng',
    tags: ['Khẩn cấp', 'Cần kiểm tra AI'],
    loaiDon: 'Hồ sơ cấp phép xây dựng',
    luotNhanId: 'LN-2025-0430',
    aiStatus: 'needs_review',
    aiReviewNote: 'Độ tin cậy 68% - Đơn có dấu hiệu chồng lấn chỉ giới xây dựng với ngõ đi chung',
    taskReadiness: 'needs_review',
  },

  // 2. Lượt nhận AI ĐÃ PHÂN TÍCH (Đã chuyển đến - Sẵn sàng tiếp nhận & xử lý)
  {
    id: 'LN-56/2026-GOVEX',
    code: 'LN-56/2026-GOVEX',
    title: 'Phản ánh ô nhiễm môi trường',
    sender: 'Đại diện khu dân cư số 4',
    source: 'Cổng DVC Quốc gia (Đã chuyển đến)',
    timeReceived: '16/09/2026 09:15',
    priority: 'normal',
    deadlineType: 'today',
    deadlineText: 'Còn 4 giờ 25 phút',
    deadlineFull: 'Hôm nay - 16:00',
    column: 'action_required',
    nextAction: 'Kiểm tra kết quả AI và tiếp nhận thụ lý',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Tổ Tiếp nhận hồ sơ',
    },
    progress: {
      currentStep: 1,
      totalSteps: 5,
      stepName: 'Xác định hướng xử lý',
      steps: ['Tiếp nhận DVC', 'AI phân tích', 'Xác định hướng', 'Thụ lý', 'Trả kết quả'],
    },
    docCount: 3,
    cta: {
      label: 'Tiếp nhận ngay',
      actionType: 'handle_now',
      variant: 'urgent',
    },
    category: 'Môi trường',
    tags: ['Đã chuyển đến', 'AI đã phân tích', 'Môi trường'],
    loaiDon: 'Đơn phản ánh kiến nghị',
    luotNhanId: 'LN-56/2026-GOVEX',
    aiStatus: 'completed',
    taskReadiness: 'action_required',
  },

  // 3. Lượt nhận AI ĐANG PHÂN TÍCH (Đã chuyển đến - Asynchronous 75%)
  {
    id: 'LN-57/2026-GOVEX',
    code: 'LN-57/2026-GOVEX',
    title: 'Đề nghị hỗ trợ an sinh xã hội',
    sender: 'Bà Hoàng Thị Lựu',
    source: 'Cổng DVC Quốc gia (VNeID) (Đã chuyển đến)',
    timeReceived: '16/09/2026 10:20',
    priority: 'normal',
    deadlineType: 'today',
    deadlineText: 'Hôm nay - 17:00',
    deadlineFull: 'Hôm nay - 17:00',
    column: 'action_required',
    nextAction: 'Đang xử lý nội dung... (Chờ AI hoàn tất)',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Tổ Tiếp nhận hồ sơ',
    },
    progress: {
      currentStep: 1,
      totalSteps: 5,
      stepName: 'AI đang bóc tách',
      steps: ['Tiếp nhận VNeID', 'AI phân tích', 'Đối soát CSDL', 'Quyết định trợ cấp', 'Chi trả'],
    },
    docCount: 4,
    cta: {
      label: 'Xem hồ sơ',
      actionType: 'view_doc',
      variant: 'outline',
    },
    category: 'Lao động - TBXH',
    tags: ['Đã chuyển đến', 'AI đang xử lý', 'VNeID'],
    loaiDon: 'Thủ tục chính sách xã hội',
    luotNhanId: 'LN-57/2026-GOVEX',
    aiStatus: 'processing',
    aiProgress: 75,
    taskReadiness: 'waiting_system',
  },

  // 4. Lượt nhận AI PHÂN TÍCH THẤT BẠI (Đã chuyển đến - OCR lỗi)
  {
    id: 'LN-58/2026-GOVEX',
    code: 'LN-58/2026-GOVEX',
    title: 'Phản ánh về đất đai',
    sender: 'Ông Đỗ Viết Thắng',
    source: 'Một cửa chuyển đến',
    timeReceived: '16/09/2026 08:45',
    priority: 'urgent',
    deadlineType: 'today',
    deadlineText: 'Hôm nay - 16:30',
    deadlineFull: 'Hôm nay - 16:30',
    column: 'action_required',
    nextAction: 'Xử lý và phân loại thủ công',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Tổ Tiếp nhận hồ sơ',
    },
    progress: {
      currentStep: 1,
      totalSteps: 5,
      stepName: 'Xử lý thủ công',
      steps: ['Tiếp nhận', 'Phân loại thủ công', 'Xác minh thực địa', 'Biên bản', 'Xử lý vi phạm'],
    },
    docCount: 2,
    cta: {
      label: 'Xử lý thủ công',
      actionType: 'manual_process',
      variant: 'urgent',
    },
    category: 'Xây dựng - Đất đai',
    tags: ['Đã chuyển đến', 'AI lỗi', 'Xử lý thủ công'],
    loaiDon: 'Đơn phản ánh kiến nghị',
    luotNhanId: 'LN-58/2026-GOVEX',
    aiStatus: 'failed',
    aiFailureReason: 'Tài liệu scan bị nghiêng và mờ, module OCR không đọc được nội dung chứng cứ kèm theo',
    taskReadiness: 'manual_required',
  },

  // ================= COLUMN 2: TIẾP NHẬN & XỬ LÝ (2 việc) =================
  {
    id: 'Đ-2025-0105',
    code: 'Đ-2025-0105',
    title: 'Thẩm tra thay đổi ngành nghề HKD cá thể',
    sender: 'Vũ Thị Thanh',
    source: 'Cổng DVC Quốc gia',
    timeReceived: '16/09/2026 09:30',
    priority: 'normal',
    deadlineType: 'upcoming',
    deadlineText: 'Còn 1 ngày (10:00 ngày mai)',
    deadlineFull: 'Ngày mai - 10:00',
    column: 'processing',
    nextAction: 'Rà soát mã ngành kinh doanh có điều kiện theo danh mục',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Phòng Tiếp công dân & Xử lý đơn',
    },
    progress: {
      currentStep: 3,
      totalSteps: 5,
      stepName: 'Thẩm tra mã ngành',
      steps: ['Tiếp nhận', 'Phân loại', 'Thẩm tra', 'Duyệt cấp', 'Trả kết quả'],
    },
    docCount: 3,
    cta: {
      label: 'Mở xử lý',
      actionType: 'continue',
      variant: 'primary',
    },
    category: 'Hộ kinh doanh',
    tags: ['Đã phân công', 'Đang xử lý'],
    loaiDon: 'Đơn đăng ký kinh doanh cá thể',
    luotNhanId: 'LN-2025-0105',
    nguoiGiao: 'Trần Trọng Giáp (Trưởng phòng)',
    ngayDuocGiao: '16/09/2026',
    aiStatus: 'completed',
    taskReadiness: 'action_required',
  },
  {
    id: 'KN-2026-0882',
    code: 'KN-2026-0882',
    title: 'Khiếu nại phương án bồi thường GPMB dự án QL1A',
    sender: 'Lê Văn Hùng',
    source: 'Trực tiếp Tiếp dân',
    timeReceived: '15/09/2026 09:15',
    priority: 'normal',
    deadlineType: 'upcoming',
    deadlineText: 'Còn 2 ngày',
    deadlineFull: '19/09/2026 17:00',
    column: 'processing',
    nextAction: 'Yêu cầu công dân bổ sung bản sao chứng thực quyền sở hữu đất',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Phòng Tiếp công dân & Xử lý đơn',
    },
    progress: {
      currentStep: 2,
      totalSteps: 5,
      stepName: 'Thu thập chứng cứ',
      steps: ['Tiếp nhận', 'Thu thập tài liệu', 'Đối thoại', 'Ban hành QĐ', 'Lưu trữ'],
    },
    docCount: 6,
    cta: {
      label: 'Mở xử lý',
      actionType: 'continue',
      variant: 'primary',
    },
    category: 'Khiếu nại',
    tags: ['Đã phân công', 'Đang xử lý'],
    loaiDon: 'Đơn khiếu nại đất đai',
    luotNhanId: 'LN-45/2026-GOVEX',
    nguoiGiao: 'Trần Trọng Giáp (Trưởng phòng)',
    ngayDuocGiao: '15/09/2026',
    aiStatus: 'completed',
    taskReadiness: 'action_required',
  },

  // ================= COLUMN 3: ĐANG CHỜ (2 việc) =================
  {
    id: 'VV-2025-0612',
    code: 'VV-2025-0612',
    title: 'Tờ trình cấp đổi GCN QSDĐ phôi 2025 cho 14 hộ dân',
    sender: 'Phạm Quốc Tuấn (Đại diện 14 hộ)',
    source: 'Một cửa liên thông',
    timeReceived: '14/09/2026 14:00',
    priority: 'urgent',
    deadlineType: 'overdue',
    deadlineText: 'Quá hạn 1 ngày',
    deadlineFull: 'Hôm qua - 17:00',
    column: 'waiting',
    nextAction: 'Chờ Lãnh đạo UBND quận phê duyệt và ký số Tờ trình',
    holder: {
      role: 'Đang chờ',
      name: 'Đ/c Nguyễn Văn Cường (Chánh VP UBND)',
      department: 'Văn phòng HĐND & UBND',
    },
    progress: {
      currentStep: 4,
      totalSteps: 5,
      stepName: 'Trình lãnh đạo ký duyệt',
      steps: ['Tiếp nhận', 'Lập tờ trình', 'Ký nháy', 'Lãnh đạo ký', 'Trả kết quả'],
    },
    docCount: 7,
    cta: {
      label: 'Xem hồ sơ',
      actionType: 'view_doc',
      variant: 'outline',
    },
    category: 'Đất đai',
    tags: ['Chờ ký duyệt', 'Cấp đổi sổ'],
    loaiDon: 'Vụ việc cấp đổi đất đai',
    luotNhanId: 'LN-2025-0612',
    aiStatus: 'none',
    taskReadiness: 'waiting_system',
  },
  {
    id: 'Đ-2025-0982',
    code: 'Đ-2025-0982',
    title: 'Cấp phép thi công biển hiệu quảng cáo tấm lớn ngã tư Sở',
    sender: 'Cty Quảng cáo Ánh Dương',
    source: 'DVC Trực tuyến',
    timeReceived: '15/09/2026 09:40',
    priority: 'normal',
    deadlineType: 'today',
    deadlineText: 'Hôm nay - 15:00',
    deadlineFull: 'Hôm nay - 15:00',
    column: 'waiting',
    nextAction: 'Chờ ý kiến thẩm định quy hoạch từ Phòng Quản lý đô thị',
    holder: {
      role: 'Đang chờ',
      name: 'Phòng Quản lý đô thị (Đ/c Trần Minh Đức)',
      department: 'Phòng Quản lý đô thị',
    },
    progress: {
      currentStep: 3,
      totalSteps: 5,
      stepName: 'Lấy ý kiến phối hợp',
      steps: ['Tiếp nhận', 'Phân công', 'Lấy ý kiến', 'Cấp giấy phép', 'Trả kết quả'],
    },
    docCount: 4,
    cta: {
      label: 'Xem tiến độ',
      actionType: 'view_progress',
      variant: 'outline',
    },
    category: 'Văn hóa - TT',
    tags: ['Chờ phối hợp', 'Quảng cáo'],
    loaiDon: 'Thủ tục cấp phép quảng cáo',
    luotNhanId: 'LN-2025-0982',
    aiStatus: 'none',
    taskReadiness: 'waiting_system',
  },

  // ================= COLUMN 4: ĐÃ BÀN GIAO / THEO DÕI (2 việc) =================
  {
    id: 'Đ-2025-1109',
    code: 'Đ-2025-1109',
    title: 'Trả kết quả bản sao chứng thực hợp đồng ủy quyền chuyển nhượng',
    sender: 'Hoàng Minh Châu',
    source: 'Bộ phận Một cửa',
    timeReceived: '16/09/2026 14:15',
    priority: 'normal',
    deadlineType: 'normal',
    deadlineText: 'Còn 3 ngày',
    deadlineFull: '21/09/2026 16:00',
    column: 'handed_over',
    nextAction: 'Bộ phận Một cửa đối chiếu bản chính và bàn giao trực tiếp cho công dân',
    holder: {
      role: 'Đã bàn giao cho',
      name: 'Cán bộ Lê Thị Thảo (Bộ phận Một cửa)',
      department: 'Bộ phận Tiếp nhận & Trả kết quả',
    },
    progress: {
      currentStep: 5,
      totalSteps: 5,
      stepName: 'Chờ công dân nhận kết quả',
      steps: ['Tiếp nhận', 'Chứng thực', 'Đóng dấu', 'Chuyển Một cửa', 'Đã nhận'],
    },
    docCount: 2,
    cta: {
      label: 'Xem tiến độ',
      actionType: 'view_progress',
      variant: 'neutral',
    },
    category: 'Tư pháp',
    tags: ['Đã bàn giao', 'Chứng thực'],
    loaiDon: 'Thủ tục chứng thực',
    luotNhanId: 'LN-2025-1109',
    aiStatus: 'none',
    taskReadiness: 'completed',
  },
  {
    id: 'TG-2026-0044',
    code: 'TG-2026-0044',
    title: 'Nguồn tin tố giác tội phạm: Lừa đảo huy động vốn phân lô bán nền',
    sender: 'Công dân giấu tên (Mã: CD-9912)',
    source: 'Đường dây nóng phòng chống tội phạm',
    timeReceived: '14/09/2026 10:30',
    priority: 'normal',
    deadlineType: 'normal',
    deadlineText: 'Còn 4 ngày',
    deadlineFull: '22/09/2026 17:00',
    column: 'handed_over',
    nextAction: 'Cơ quan CSĐT tiến hành xác minh tiền kiểm trong thời hạn 20 ngày',
    holder: {
      role: 'Đang xử lý',
      name: 'Trung tá Lê Văn Nam (Đội 3 - CSĐT PC03)',
      department: 'Cơ quan Cảnh sát điều tra',
    },
    progress: {
      currentStep: 2,
      totalSteps: 4,
      stepName: 'Xác minh tiền kiểm CSĐT',
      steps: ['Tiếp nhận tin', 'Phân công Điều tra viên', 'Xác minh', 'Quyết định tố tụng'],
    },
    docCount: 5,
    cta: {
      label: 'Xem tiến độ',
      actionType: 'view_progress',
      variant: 'neutral',
    },
    category: 'Tố giác tội phạm',
    tags: ['Đã bàn giao', 'CSĐT'],
    loaiDon: 'Nguồn tin tố giác tội phạm',
    luotNhanId: 'LN-2026-0044',
    aiStatus: 'none',
    taskReadiness: 'completed',
  },
];
