import { WorkItem } from '../types/work';

export const INITIAL_WORK_ITEMS: WorkItem[] = [
  // =========================================================================
  // CỘT 1: CẦN XỬ LÝ (Công việc đang đến lượt người dùng hiện tại thực hiện)
  // Bao gồm: Mới được giao, Chưa xử lý, Cần kiểm tra kết quả AI, Cần bổ sung thông tin,
  // Bị trả lại, Cần xác nhận, Cần trình ký...
  // =========================================================================

  // 1. [Đơn] Đ-2026-0098 - Kiểm tra kết quả AI (Khớp ví dụ người dùng)
  {
    id: 'Đ-2026-0098',
    code: 'Đ-2026-0098',
    title: 'Thẩm định hồ sơ chuyển đổi ngành nghề kinh doanh HKD cá thể',
    sender: 'Vũ Thị Thanh',
    source: 'Cổng DVC Quốc gia',
    sourceType: 'don',
    actionTitle: 'Kiểm tra kết quả AI',
    subStatus: 'can_kiem_tra_ai',
    timeReceived: '23/09/2026 08:30',
    priority: 'high',
    deadlineType: 'upcoming',
    deadlineText: '25/09/2026',
    deadlineFull: '25/09/2026 17:00',
    column: 'action_required',
    nextAction: 'Kiểm tra và xác nhận đối soát mã ngành nghề từ AI',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Phòng Tiếp công dân & Xử lý đơn',
    },
    departmentId: 'tiep-dan',
    departmentName: 'Phòng Tiếp công dân & Xử lý đơn',
    progress: {
      currentStep: 2,
      totalSteps: 5,
      stepName: 'Kiểm tra kết quả AI',
      steps: ['Tiếp nhận', 'Kiểm tra kết quả AI', 'Thẩm tra mã ngành', 'Trình ký', 'Trả kết quả'],
    },
    docCount: 3,
    cta: {
      label: 'Kiểm tra',
      actionType: 'review_ai',
      variant: 'warning',
    },
    category: 'Hộ kinh doanh',
    tags: ['AI cần kiểm tra', 'Sắp quá hạn'],
    loaiDon: 'Đơn đăng ký kinh doanh cá thể',
    luotNhanId: 'LN-2026-0098',
    aiStatus: 'needs_review',
    aiReviewNote: 'Độ tin cậy 74% - Ngành nghề bán lẻ thực phẩm chức năng cần kiểm tra giấy phép con',
    taskReadiness: 'needs_review',
  },

  // 2. Lượt nhận AI ĐÃ PHÂN TÍCH (Đã chuyển đến - Sẵn sàng tiếp nhận & xử lý)
  {
    id: 'LN-56/2026-GOVEX',
    code: 'LN-56/2026-GOVEX',
    title: 'Phản ánh ô nhiễm môi trường',
    sender: 'Đại diện khu dân cư số 4',
    source: 'Cổng DVC Quốc gia (Đã chuyển đến)',
    timeReceived: '16/09/2026 09:15',
    priority: 'normal',
    deadlineType: 'today',
    deadlineText: 'Hôm nay 17:30',
    deadlineFull: 'Hôm nay - 17:30',
    column: 'action_required',
    nextAction: 'Kiểm tra kết quả AI và tiếp nhận thụ lý',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Tổ Tiếp nhận hồ sơ',
    },
    departmentId: 'tiep-dan',
    departmentName: 'Phòng Tiếp công dân & Xử lý đơn',
    progress: {
      currentStep: 1,
      totalSteps: 4,
      stepName: 'Tiếp nhận lượt nhận',
      steps: ['Tiếp nhận', 'Bóc tách dữ liệu', 'Chuyển tiếp nhận', 'Vào sổ theo dõi'],
    },
    docCount: 4,
    cta: {
      label: 'Tiếp nhận ngay',
      actionType: 'handle_now',
      variant: 'urgent',
    },
    category: 'Môi trường',
    tags: ['Đã chuyển đến', 'AI đã phân tích', 'Môi trường'],
    loaiDon: 'Đơn phản ánh kiến nghị',
    luotNhanId: 'LR-2026-0012',
    aiStatus: 'completed',
    taskReadiness: 'action_required',
  },

  // 3. Lượt nhận AI ĐANG PHÂN TÍCH (Đã chuyển đến - Asynchronous 75%)
  {
    id: 'LN-57/2026-GOVEX',
    code: 'LN-57/2026-GOVEX',
    title: 'Đề nghị hỗ trợ an sinh xã hội',
    sender: 'Bà Hoàng Thị Lựu',
    source: 'Cổng DVC Quốc gia (VNeID) (Đã chuyển đến)',
    timeReceived: '16/09/2026 10:20',
    priority: 'normal',
    deadlineType: 'today',
    deadlineText: 'Hôm nay - 17:00',
    deadlineFull: 'Hôm nay - 17:00',
    column: 'action_required',
    nextAction: 'Phân loại và xác định thẩm quyền xử lý tố giác tội phạm',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Phòng Tiếp công dân & Xử lý đơn',
    },
    departmentId: 'tiep-dan',
    departmentName: 'Phòng Tiếp công dân & Xử lý đơn',
    progress: {
      currentStep: 2,
      totalSteps: 5,
      stepName: 'Xác định thẩm quyền',
      steps: ['Tiếp nhận', 'Kiểm tra AI', 'Xác định hướng', 'Trình lãnh đạo', 'Bàn giao CSĐT'],
    },
    docCount: 8,
    cta: {
      label: 'Kiểm tra',
      actionType: 'review_ai',
      variant: 'warning',
    },
    category: 'Lao động - TBXH',
    tags: ['Đã chuyển đến', 'AI đang xử lý', 'VNeID'],
    loaiDon: 'Thủ tục chính sách xã hội',
    luotNhanId: 'LN-57/2026-GOVEX',
    aiStatus: 'processing',
    aiProgress: 75,
    taskReadiness: 'waiting_system',
  },

  // 4. Lượt nhận AI PHÂN TÍCH THẤT BẠI (Đã chuyển đến - OCR lỗi)
  {
    id: 'LN-58/2026-GOVEX',
    code: 'LN-58/2026-GOVEX',
    title: 'Phản ánh về đất đai',
    sender: 'Ông Đỗ Viết Thắng',
    source: 'Một cửa chuyển đến',
    timeReceived: '16/09/2026 08:45',
    priority: 'urgent',
    deadlineType: 'today',
    deadlineText: 'Hôm nay 16:30',
    deadlineFull: 'Hôm nay - 16:30',
    column: 'action_required',
    nextAction: 'Lập phiếu hướng dẫn hoàn thiện hồ sơ đo đạc địa chính',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Phòng Tài nguyên và Môi trường',
    },
    departmentId: 'tnmt',
    departmentName: 'Phòng Tài nguyên và Môi trường',
    progress: {
      currentStep: 2,
      totalSteps: 5,
      stepName: 'Bổ sung hồ sơ',
      steps: ['Tiếp nhận', 'Bổ sung hồ sơ', 'Thẩm tra thực địa', 'Đối thoại', 'Ban hành kết luận'],
    },
    docCount: 3,
    cta: {
      label: 'Bổ sung',
      actionType: 'supplement',
      variant: 'primary',
    },
    category: 'Xây dựng - Đất đai',
    tags: ['Đã chuyển đến', 'AI lỗi', 'Xử lý thủ công'],
    loaiDon: 'Đơn phản ánh kiến nghị',
    luotNhanId: 'LN-58/2026-GOVEX',
    aiStatus: 'failed',
    aiFailureReason: 'Tài liệu scan bị nghiêng và mờ, module OCR không đọc được nội dung chứng cứ kèm theo',
    taskReadiness: 'manual_required',
  },

  // =========================================================================
  // CỘT 2: ĐANG THỰC HIỆN (Người dùng đã bắt đầu xử lý nhưng chưa hoàn tất)
  // =========================================================================

  // 5. [Vụ việc] VV-2026-0430 - Cho ý kiến xử lý (Khớp ví dụ người dùng)
  {
    id: 'VV-2026-0430',
    code: 'VV-2026-0430',
    title: 'Vụ việc kiểm tra an toàn thi công công trình xây dựng số 88 Thụy Khuê',
    sender: 'Ban Quản trị chung cư Golden Westlake',
    source: 'Đường dây nóng UBND',
    sourceType: 'vu_viec',
    actionTitle: 'Cho ý kiến xử lý & thẩm định thực địa',
    subStatus: 'dang_xu_ly',
    timeReceived: '21/09/2026 10:00',
    priority: 'normal',
    deadlineType: 'normal',
    deadlineText: '27/09/2026',
    deadlineFull: '27/09/2026 17:00',
    column: 'processing',
    nextAction: 'Kiểm tra hiện trường và lập biên bản ghi nhận nứt tường',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Phòng Quản lý Đô thị',
    },
    departmentId: 'qldt',
    departmentName: 'Phòng Quản lý Đô thị',
    progress: {
      currentStep: 3,
      totalSteps: 5,
      stepName: 'Thẩm định hiện trường',
      steps: ['Tiếp nhận', 'Phân công', 'Thẩm định hiện trường', 'Dự thảo kết luận', 'Ban hành'],
    },
    docCount: 6,
    cta: {
      label: 'Xử lý',
      actionType: 'continue',
      variant: 'primary',
    },
    category: 'Xây dựng - Đô thị',
    tags: ['Đang xử lý', 'Trong hạn'],
    loaiDon: 'Vụ việc vi phạm xây dựng',
    luotNhanId: 'LN-2026-0430',
    aiStatus: 'completed',
    taskReadiness: 'action_required',
  },

  // 6. [Đơn] KN-2026-0882 - Khiếu nại bồi thường GPMB
  {
    id: 'KN-2026-0882',
    code: 'KN-2026-0882',
    title: 'Khiếu nại phương án bồi thường GPMB dự án mở rộng đường Vành đai 2.5',
    sender: 'Lê Văn Hùng',
    source: 'Trực tiếp Tiếp dân',
    sourceType: 'don',
    actionTitle: 'Đối chiếu phương án giá đền bù với khung giá đất',
    subStatus: 'dang_xu_ly',
    timeReceived: '20/09/2026 09:15',
    priority: 'high',
    deadlineType: 'upcoming',
    deadlineText: 'Còn 1 ngày (Ngày mai 17:00)',
    deadlineFull: '24/09/2026 17:00',
    column: 'processing',
    nextAction: 'Dự thảo báo cáo đối thoại với công dân tại trụ sở UBND',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Phòng Tiếp công dân & Xử lý đơn',
    },
    departmentId: 'tiep-dan',
    departmentName: 'Phòng Tiếp công dân & Xử lý đơn',
    progress: {
      currentStep: 3,
      totalSteps: 5,
      stepName: 'Thu thập chứng cứ',
      steps: ['Tiếp nhận', 'Thu thập chứng cứ', 'Đối thoại', 'Dự thảo QĐ', 'Lưu trữ'],
    },
    docCount: 5,
    cta: {
      label: 'Xử lý',
      actionType: 'continue',
      variant: 'primary',
    },
    category: 'Khiếu nại đất đai',
    tags: ['Sắp quá hạn', 'Đang xử lý'],
    loaiDon: 'Đơn khiếu nại bồi thường',
    luotNhanId: 'LN-45/2026-GOVEX',
    nguoiGiao: 'Trần Trọng Giáp (Trưởng phòng)',
    ngayDuocGiao: '20/09/2026',
    aiStatus: 'completed',
    taskReadiness: 'action_required',
  },

  // 7. [Lượt nhận] LN-57/2026-GOVEX - AI đang phân tích bóc tách hồ sơ
  {
    id: 'LN-57/2026-GOVEX',
    code: 'LN-57/2026-GOVEX',
    title: 'Đề nghị hỗ trợ trợ cấp mai táng đối tượng chính sách xã hội',
    sender: 'Bà Hoàng Thị Lựu',
    source: 'Cổng DVC Quốc gia (VNeID)',
    sourceType: 'luot_nhan',
    actionTitle: 'Bóc tách dữ liệu điện tử & đối soát CSDL dân cư',
    subStatus: 'dang_xu_ly',
    timeReceived: '23/09/2026 10:20',
    priority: 'normal',
    deadlineType: 'today',
    deadlineText: 'Hôm nay 17:00',
    deadlineFull: 'Hôm nay - 17:00',
    column: 'processing',
    nextAction: 'Theo dõi tiến trình bóc tách OCR và trích xuất trường tự động',
    holder: {
      role: 'Đang xử lý',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Tổ Tiếp nhận hồ sơ',
    },
    departmentId: 'tiep-dan',
    departmentName: 'Phòng Tiếp công dân & Xử lý đơn',
    progress: {
      currentStep: 2,
      totalSteps: 5,
      stepName: 'AI đang bóc tách',
      steps: ['Tiếp nhận VNeID', 'AI bóc tách', 'Đối soát CSDL', 'Duyệt trợ cấp', 'Chi trả'],
    },
    docCount: 4,
    cta: {
      label: 'Xem hồ sơ',
      actionType: 'view_doc',
      variant: 'outline',
    },
    category: 'Chính sách xã hội',
    tags: ['AI đang phân tích', 'VNeID'],
    loaiDon: 'Thủ tục trợ cấp xã hội',
    luotNhanId: 'LN-57/2026-GOVEX',
    aiStatus: 'processing',
    aiProgress: 75,
    taskReadiness: 'waiting_system',
  },

  // =========================================================================
  // CỘT 3: ĐANG CHỜ (Đã hoàn thành phần việc, chờ tác nhân khác: Ký, Phê duyệt, Phối hợp, Hệ thống)
  // =========================================================================

  // 8. [Vụ việc] VV-2025-0612 - Chờ lãnh đạo duyệt & ký số
  {
    id: 'VV-2025-0612',
    code: 'VV-2025-0612',
    title: 'Tờ trình phê duyệt cấp đổi GCN QSDĐ phôi 2026 cho 14 hộ dân Cống Vị',
    sender: 'Phạm Quốc Tuấn (Đại diện 14 hộ)',
    source: 'Một cửa liên thông',
    sourceType: 'vu_viec',
    actionTitle: 'Chờ lãnh đạo duyệt & ký số',
    subStatus: 'cho_phe_duyet',
    timeReceived: '19/09/2026 14:00',
    priority: 'urgent',
    deadlineType: 'overdue',
    deadlineText: 'Quá hạn 1 ngày',
    deadlineFull: 'Hôm qua - 17:00',
    column: 'waiting',
    nextAction: 'Chờ Đ/c Nguyễn Văn Cường (Chánh VP UBND) ký duyệt',
    holder: {
      role: 'Đang chờ',
      name: 'Đ/c Nguyễn Văn Cường (Chánh VP UBND)',
      department: 'Văn phòng HĐND & UBND',
    },
    departmentId: 'qldt',
    departmentName: 'Văn phòng UBND Quận',
    progress: {
      currentStep: 4,
      totalSteps: 5,
      stepName: 'Trình lãnh đạo ký',
      steps: ['Tiếp nhận', 'Lập tờ trình', 'Ký nháy', 'Lãnh đạo ký', 'Trả kết quả'],
    },
    docCount: 7,
    cta: {
      label: 'Xem hồ sơ',
      actionType: 'view_doc',
      variant: 'outline',
    },
    category: 'Đất đai',
    tags: ['Chờ phê duyệt', 'Quá hạn'],
    loaiDon: 'Vụ việc cấp đổi đất đai',
    luotNhanId: 'LN-2025-0612',
    aiStatus: 'none',
    taskReadiness: 'waiting_system',
  },

  // 9. [Đơn] Đ-2025-0982 - Chờ đơn vị phối hợp (Ý kiến quy hoạch Phòng QL Đô thị)
  {
    id: 'Đ-2025-0982',
    code: 'Đ-2025-0982',
    title: 'Thẩm định cấp phép thi công biển hiệu quảng cáo tấm lớn ngã tư Kim Mã',
    sender: 'Cty TNHH Truyền thông Ánh Dương',
    source: 'DVC Trực tuyến',
    sourceType: 'don',
    actionTitle: 'Chờ đơn vị phối hợp thẩm định quy hoạch',
    subStatus: 'cho_phoi_hop',
    timeReceived: '22/09/2026 09:40',
    priority: 'normal',
    deadlineType: 'today',
    deadlineText: 'Hôm nay 15:00',
    deadlineFull: 'Hôm nay - 15:00',
    column: 'waiting',
    nextAction: 'Chờ văn bản trả lời thẩm định quy hoạch đô thị từ Phòng QL Đô thị',
    holder: {
      role: 'Đang chờ',
      name: 'Phòng Quản lý đô thị (Đ/c Trần Minh Đức)',
      department: 'Phòng Quản lý đô thị',
    },
    departmentId: 'qldt',
    departmentName: 'Phòng Quản lý Đô thị',
    progress: {
      currentStep: 3,
      totalSteps: 5,
      stepName: 'Lấy ý kiến phối hợp',
      steps: ['Tiếp nhận', 'Phân công', 'Lấy ý kiến', 'Cấp giấy phép', 'Trả kết quả'],
    },
    docCount: 4,
    cta: {
      label: 'Xem tiến độ',
      actionType: 'view_progress',
      variant: 'outline',
    },
    category: 'Văn hóa - TT',
    tags: ['Chờ phối hợp', 'Hôm nay'],
    loaiDon: 'Thủ tục cấp phép quảng cáo',
    luotNhanId: 'LN-2025-0982',
    aiStatus: 'none',
    taskReadiness: 'waiting_system',
  },

  // 10. [Đơn] Đ-2025-0321 - Chờ bổ sung hồ sơ từ công dân
  {
    id: 'Đ-2025-0321',
    code: 'Đ-2025-0321',
    title: 'Đăng ký biến động quyền sử dụng đất tặng cho con ruột',
    sender: 'Ngô Quốc Bảo',
    source: 'Bộ phận Một cửa',
    sourceType: 'don',
    actionTitle: 'Chờ công dân nộp bổ sung bản sao chứng thực sổ đỏ',
    subStatus: 'can_bo_sung',
    timeReceived: '21/09/2026 15:30',
    priority: 'normal',
    deadlineType: 'normal',
    deadlineText: '28/09/2026',
    deadlineFull: '28/09/2026 17:00',
    column: 'waiting',
    nextAction: 'Chờ công dân mang bản gốc và bản công chứng đối chiếu',
    holder: {
      role: 'Đang chờ',
      name: 'Công dân (Ngô Quốc Bảo)',
      department: 'Bộ phận Tiếp nhận & Trả kết quả',
    },
    departmentId: 'tiep-dan',
    departmentName: 'Bộ phận Một cửa',
    progress: {
      currentStep: 2,
      totalSteps: 5,
      stepName: 'Chờ bổ sung giấy tờ',
      steps: ['Tiếp nhận', 'Bổ sung giấy tờ', 'Thẩm định hồ sơ', 'Ký giấy xác nhận', 'Trả kết quả'],
    },
    docCount: 3,
    cta: {
      label: 'Xem hồ sơ',
      actionType: 'view_doc',
      variant: 'outline',
    },
    category: 'Đất đai',
    tags: ['Cần bổ sung', 'Trong hạn'],
    loaiDon: 'Thủ tục biến động đất đai',
    luotNhanId: 'LN-2025-0321',
    aiStatus: 'none',
    taskReadiness: 'waiting_system',
  },

  // =========================================================================
  // CỘT 4: ĐÃ BÀN GIAO (Đã chuyển đơn vị/cá nhân khác, người dùng theo dõi tiến độ)
  // =========================================================================

  // 11. [Lượt nhận] LR-2026-0005 - Đã chuyển Bộ phận Một cửa
  {
    id: 'LR-2026-0005',
    code: 'LR-2026-0005',
    title: 'Lượt nhận sao y chứng thực chữ ký giấy tờ ủy quyền',
    sender: 'Hoàng Minh Châu',
    source: 'Bộ phận Một cửa',
    sourceType: 'luot_nhan',
    actionTitle: 'Đã chuyển Bộ phận Một cửa trả kết quả',
    subStatus: 'da_ban_giao',
    timeReceived: '22/09/2026 14:15',
    priority: 'normal',
    deadlineType: 'normal',
    deadlineText: 'Còn 3 ngày',
    deadlineFull: '26/09/2026 16:00',
    column: 'handed_over',
    nextAction: 'Cán bộ Lê Thị Thảo (Một cửa) đối chiếu bản chính và bàn giao trực tiếp',
    holder: {
      role: 'Đã bàn giao cho',
      name: 'Cán bộ Lê Thị Thảo (Một cửa)',
      department: 'Bộ phận Tiếp nhận & Trả kết quả',
    },
    departmentId: 'tu-phap',
    departmentName: 'Phòng Tư pháp',
    progress: {
      currentStep: 4,
      totalSteps: 4,
      stepName: 'Chờ công dân nhận',
      steps: ['Tiếp nhận', 'Chứng thực', 'Đóng dấu', 'Bàn giao Một cửa'],
    },
    docCount: 2,
    cta: {
      label: 'Xem tiến độ',
      actionType: 'view_progress',
      variant: 'neutral',
    },
    category: 'Tư pháp',
    tags: ['Đã bàn giao'],
    loaiDon: 'Thủ tục chứng thực',
    luotNhanId: 'LR-2026-0005',
    aiStatus: 'none',
    taskReadiness: 'completed',
  },

  // 12. [Vụ việc] TG-2026-0044 - Nguồn tin tố giác chuyển Cơ quan CSĐT PC03
  {
    id: 'TG-2026-0044',
    code: 'TG-2026-0044',
    title: 'Nguồn tin tố giác tội phạm lừa đảo huy động vốn phân lô bán nền',
    sender: 'Công dân ẩn danh (Mã: CD-9912)',
    source: 'Đường dây nóng phòng chống tội phạm',
    sourceType: 'vu_viec',
    actionTitle: 'Đã bàn giao sang Cơ quan CSĐT PC03',
    subStatus: 'da_ban_giao',
    timeReceived: '18/09/2026 10:30',
    priority: 'normal',
    deadlineType: 'normal',
    deadlineText: 'Còn 4 ngày',
    deadlineFull: '27/09/2026 17:00',
    column: 'handed_over',
    nextAction: 'Cơ quan CSĐT tiến hành xác minh tiền kiểm theo thời hạn 20 ngày',
    holder: {
      role: 'Đã bàn giao cho',
      name: 'Trung tá Lê Văn Nam (Đội 3 - CSĐT PC03)',
      department: 'Cơ quan Cảnh sát điều tra',
    },
    departmentId: 'pc03',
    departmentName: 'Phòng CS Kinh tế (PC03)',
    progress: {
      currentStep: 2,
      totalSteps: 4,
      stepName: 'Xác minh tiền kiểm CSĐT',
      steps: ['Tiếp nhận tin', 'Phân công Điều tra viên', 'Xác minh', 'Quyết định tố tụng'],
    },
    docCount: 5,
    cta: {
      label: 'Xem tiến độ',
      actionType: 'view_progress',
      variant: 'neutral',
    },
    category: 'Tố giác tội phạm',
    tags: ['Đã bàn giao', 'CSĐT'],
    loaiDon: 'Nguồn tin tố giác tội phạm',
    luotNhanId: 'LN-2026-0044',
    aiStatus: 'none',
    taskReadiness: 'completed',
  },

  // =========================================================================
  // CÁC HỒ SƠ ĐÃ HOÀN THÀNH (Đưa vào tab/lịch sử riêng, không chiếm cột Kanban)
  // =========================================================================
  {
    id: 'Đ-2025-1109',
    code: 'Đ-2025-1109',
    title: 'Cấp trích lục khai sinh cho công dân Nguyễn Hoài Anh',
    sender: 'Nguyễn Hoài Anh',
    source: 'Cổng DVC Quốc gia',
    sourceType: 'don',
    actionTitle: 'Đã hoàn tất trả kết quả điện tử và lưu trữ hồ sơ',
    subStatus: 'da_hoan_thanh',
    timeReceived: '14/09/2026 09:00',
    priority: 'normal',
    deadlineType: 'normal',
    deadlineText: 'Đã hoàn thành',
    deadlineFull: '16/09/2026 11:30',
    column: 'completed',
    nextAction: 'Hồ sơ đã lưu trữ văn thư số',
    holder: {
      role: 'Đã hoàn thành',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Phòng Tư pháp',
    },
    departmentId: 'tu-phap',
    departmentName: 'Phòng Tư pháp',
    progress: {
      currentStep: 5,
      totalSteps: 5,
      stepName: 'Đã hoàn thành',
      steps: ['Tiếp nhận', 'Tra cứu CSDL', 'Ký số', 'Gửi DVC', 'Lưu trữ'],
    },
    docCount: 2,
    cta: {
      label: 'Xem kết quả',
      actionType: 'view_doc',
      variant: 'neutral',
    },
    category: 'Hộ tịch',
    tags: ['Đã hoàn thành'],
    loaiDon: 'Thủ tục hộ tịch',
    luotNhanId: 'LN-2025-1109',
    completedAt: '16/09/2026 10:45',
    completionResult: 'Đã cấp bản điện tử có chữ ký số công quyền, công dân tải thành công từ VNeID.',
    aiStatus: 'completed',
  },
  {
    id: 'VV-2025-0210',
    code: 'VV-2025-0210',
    title: 'Hòa giải tranh chấp quyền sử dụng diện tích chung ngõ 18 Nguyễn Du',
    sender: 'Tổ dân phố số 2 Phường Nguyễn Du',
    source: 'UBND Phường gửi lên',
    sourceType: 'vu_viec',
    actionTitle: 'Đã ký biên bản hòa giải thành công và lưu trữ vụ việc',
    subStatus: 'da_hoan_thanh',
    timeReceived: '10/09/2026 08:30',
    priority: 'normal',
    deadlineType: 'normal',
    deadlineText: 'Đã hoàn thành',
    deadlineFull: '18/09/2026 16:00',
    column: 'completed',
    nextAction: 'Đã ban hành thông báo kết quả hòa giải đến các bên',
    holder: {
      role: 'Đã hoàn thành',
      name: 'Tôi (Nguyễn Minh Anh)',
      department: 'Phòng Tiếp công dân & Xử lý đơn',
    },
    departmentId: 'tiep-dan',
    departmentName: 'Phòng Tiếp công dân & Xử lý đơn',
    progress: {
      currentStep: 5,
      totalSteps: 5,
      stepName: 'Đã hoàn thành',
      steps: ['Thụ lý', 'Khảo sát', 'Tổ chức đối thoại', 'Lập biên bản', 'Lưu trữ'],
    },
    docCount: 6,
    cta: {
      label: 'Xem hồ sơ',
      actionType: 'view_doc',
      variant: 'neutral',
    },
    category: 'Hòa giải tranh chấp',
    tags: ['Đã hoàn thành'],
    loaiDon: 'Vụ việc hòa giải',
    luotNhanId: 'LN-2025-0210',
    completedAt: '18/09/2026 15:30',
    completionResult: 'Các bên đồng thuận mốc giới và ký biên bản hòa giải thành công.',
    aiStatus: 'completed',
  },
];
