// src/screens/workflowAdmin/templates/workflowTemplates.ts
import { ProcessWorkflow } from '../../../types/workflowConfig';

export interface WorkflowTemplateMeta {
  id: string;
  name: string;
  codePrefix: string;
  loaiDonId: string;
  loaiDonName: string;
  description: string;
  category: 'DON_THU' | 'VAN_BAN' | 'NOI_BO';
  icon: string;
  badgeColor: string;
  stepsCount: number;
  lanesCount: number;
  workflow: ProcessWorkflow;
}

export const WORKFLOW_TEMPLATES: WorkflowTemplateMeta[] = [
  // 1. Quy trình xử lý đơn cơ bản
  {
    id: 'tpl-basic',
    name: 'Quy trình xử lý đơn cơ bản',
    codePrefix: 'QT-CB',
    loaiDonId: 'don-chung',
    loaiDonName: 'Đơn thư thông thường',
    description: 'Quy trình 3 bước chuẩn hóa: Tiếp nhận → Thụ lý giải quyết → Phê duyệt & Ban hành kết quả.',
    category: 'DON_THU',
    icon: 'account_tree',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-200',
    stepsCount: 3,
    lanesCount: 3,
    workflow: {
      id: 'tpl-basic-wf',
      code: 'QT-CB-2026-001',
      name: 'Quy trình xử lý đơn cơ bản',
      loaiDonId: 'don-chung',
      loaiDonName: 'Đơn thư thông thường',
      version: 'v1.0',
      status: 'draft',
      description: 'Mẫu quy trình xử lý đơn cơ bản chuẩn 3 cấp trách nhiệm.',
      updatedAt: '01/10/2026 08:00',
      updatedBy: 'Hệ thống Quản trị',
      lanes: [
        { id: 'lane-vt', name: 'Bộ phận Tiếp nhận / Một cửa', code: 'TN', order: 1, description: 'Tiếp nhận và kiểm tra ban đầu' },
        { id: 'lane-cm', name: 'Cán bộ Chuyên môn', code: 'CM', order: 2, description: 'Xác minh và xử lý vụ việc' },
        { id: 'lane-ld', name: 'Lãnh đạo đơn vị', code: 'LD', order: 3, description: 'Ký duyệt kết quả' },
      ],
      stages: [
        { id: 'stg-1', name: 'Tiếp nhận', order: 1 },
        { id: 'stg-2', name: 'Xử lý chuyên môn', order: 2 },
        { id: 'stg-3', name: 'Phê duyệt & Trả kết quả', order: 3 },
      ],
      steps: [
        {
          id: 'step-b-1',
          code: 'STEP-01',
          name: 'Tiếp nhận & Vào sổ theo dõi',
          nodeType: 'START',
          isStart: true,
          isEnd: false,
          laneId: 'lane-vt',
          stageId: 'stg-1',
          timeLimitDays: 1,
          workHours: 8,
          warningBeforeHours: 2,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          storedDocuments: ['Giấy biên nhận tiếp nhận hồ sơ'],
          stepForms: [],
          statusChangeDoc: 'Tiếp nhận thành công',
          description: 'Tiếp nhận đơn, đối chiếu hồ sơ và cấp mã tra cứu cho công dân.',
          actions: [
            { id: 'act-b-1', code: 'TRANSFER', label: 'Chuyển thụ lý', type: 'COMPLETE' },
          ],
        },
        {
          id: 'step-b-2',
          code: 'STEP-02',
          name: 'Thực hiện xử lý chuyên môn',
          nodeType: 'TASK',
          isStart: false,
          isEnd: false,
          laneId: 'lane-cm',
          stageId: 'stg-2',
          timeLimitDays: 10,
          workHours: 80,
          warningBeforeHours: 16,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          storedDocuments: ['Báo cáo kết quả xử lý chuyên môn'],
          stepForms: [],
          statusChangeDoc: 'Báo cáo xử lý',
          description: 'Thực hiện nghiệp vụ chuyên môn, xác minh thực tế và lập hồ sơ xử lý.',
          actions: [
            { id: 'act-b-2', code: 'SUBMIT', label: 'Trình lãnh đạo', type: 'APPROVE' },
            { id: 'act-b-3', code: 'REQ_MORE', label: 'Yêu cầu bổ sung', type: 'REQUEST_INFO' },
          ],
          aiConfig: {
            enabled: true,
            capabilities: ['OCR', 'EXTRACT', 'SUGGEST'],
            requireUserConfirmation: true,
          },
        },
        {
          id: 'step-b-3',
          code: 'STEP-03',
          name: 'Lãnh đạo phê duyệt và trả kết quả',
          nodeType: 'APPROVAL',
          isStart: false,
          isEnd: true,
          laneId: 'lane-ld',
          stageId: 'stg-3',
          timeLimitDays: 3,
          workHours: 24,
          warningBeforeHours: 4,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          storedDocuments: ['Văn bản trả lời chính thức đã ký số'],
          stepForms: [],
          statusChangeDoc: 'Văn bản kết quả hoàn tất',
          description: 'Lãnh đạo ký số phê duyệt kết quả xử lý và chuyển ban hành.',
          approvalConfig: {
            approvalStyle: 'SINGLE',
            authorityRole: 'Lãnh đạo cơ quan',
          },
          actions: [
            { id: 'act-b-4', code: 'APPROVE', label: 'Phê duyệt ban hành', type: 'APPROVE' },
            { id: 'act-b-5', code: 'REJECT', label: 'Yêu cầu sửa lại', type: 'REVISE' },
          ],
        },
      ],
      transitions: [
        {
          id: 'trans-b-1',
          actionName: 'Chuyển chuyên môn',
          fromStepId: 'step-b-1',
          toStepId: 'step-b-2',
          type: 'normal',
          allowedRoles: ['Cán bộ Tiếp nhận'],
          createNextTask: true,
          taskAssigneeRole: 'Cán bộ Chuyên môn',
          conditions: [],
        },
        {
          id: 'trans-b-2',
          actionName: 'Trình phê duyệt',
          fromStepId: 'step-b-2',
          toStepId: 'step-b-3',
          type: 'normal',
          allowedRoles: ['Cán bộ Chuyên môn'],
          createNextTask: true,
          taskAssigneeRole: 'Lãnh đạo đơn vị',
          conditions: [],
        },
      ],
      versionHistory: [
        {
          version: 'v1.0',
          publishedAt: 'Mẫu có sẵn',
          publishedBy: 'Hệ thống',
          notes: 'Mẫu quy trình cơ bản',
          isCurrentActive: true,
        },
      ],
    },
  },

  // 2. Quy trình khiếu nại
  {
    id: 'tpl-khieu-nai',
    name: 'Quy trình giải quyết khiếu nại',
    codePrefix: 'QT-KN',
    loaiDonId: 'khieu-nai',
    loaiDonName: 'Khiếu nại',
    description: 'Quy trình giải quyết khiếu nại hành chính theo Luật Khiếu nại 2011: Thụ lý → Đối thoại → Quyết định giải quyết.',
    category: 'DON_THU',
    icon: 'gavel',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    stepsCount: 5,
    lanesCount: 3,
    workflow: {
      id: 'tpl-kn-wf',
      code: 'QT-KN-2026-001',
      name: 'Quy trình giải quyết đơn khiếu nại',
      loaiDonId: 'khieu-nai',
      loaiDonName: 'Khiếu nại',
      version: 'v1.0',
      status: 'draft',
      description: 'Quy trình giải quyết khiếu nại hành chính, đối thoại và ban hành quyết định giải quyết khiếu nại.',
      updatedAt: '01/10/2026 08:30',
      updatedBy: 'Hệ thống Quản trị',
      lanes: [
        { id: 'lane-cv', name: 'Chuyên viên thụ lý', code: 'CV', order: 1, description: 'Tiếp nhận, xác minh và tổ chức đối thoại' },
        { id: 'lane-ld', name: 'Lãnh đạo có thẩm quyền', code: 'LD', order: 2, description: 'Chủ trì đối thoại và ký quyết định' },
      ],
      stages: [
        { id: 'stg-1', name: 'Tiếp nhận & Thụ lý', order: 1 },
        { id: 'stg-2', name: 'Xác minh nội dung', order: 2 },
        { id: 'stg-3', name: 'Tổ chức đối thoại', order: 3 },
        { id: 'stg-4', name: 'Ban hành quyết định', order: 4 },
      ],
      steps: [
        {
          id: 'step-kn-1',
          code: 'STEP-KN-01',
          name: 'Tiếp nhận & Kiểm tra điều kiện thụ lý',
          nodeType: 'CHECK',
          isStart: true,
          isEnd: false,
          laneId: 'lane-cv',
          stageId: 'stg-1',
          timeLimitDays: 2,
          workHours: 16,
          warningBeforeHours: 4,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          inheritedFromId: 'std-check',
          inheritedFromName: 'Kiểm tra điều kiện thụ lý',
          isCustomized: false,
          conditions: [
            'Người khiếu nại được xác định',
            'Có nội dung khiếu nại',
            'Có đối tượng bị khiếu nại',
            'Thuộc thẩm quyền',
          ],
          conditionsOverride: false,
          stepForms: ['Phiếu kiểm tra điều kiện thụ lý'],
          formsOverride: false,
          inputDocuments: ['Đơn khiếu nại'],
          inputDocsOverride: false,
          storedDocuments: ['Phiếu tiếp nhận đơn khiếu nại'],
          outputDocsOverride: false,
          statusChangeDoc: 'Thông báo thụ lý khiếu nại',
          description: 'Kiểm tra thẩm quyền, thời hiệu và 4 điều kiện thụ lý ban đầu theo Luật Khiếu nại.',
          actions: [
            { id: 'act-kn-1', code: 'VALID', label: 'Đủ điều kiện thụ lý', type: 'COMPLETE' },
            { id: 'act-kn-2', code: 'INVALID', label: 'Không đủ điều kiện', type: 'REJECT' },
            { id: 'act-kn-3', code: 'TRANSFER', label: 'Chuyển đơn đúng thẩm quyền', type: 'TRANSFER' },
          ],
          aiConfig: {
            enabled: true,
            capabilities: ['OCR', 'CHECK_CONDITION'],
            requireUserConfirmation: true,
            promptDescription: 'Tự động kiểm tra 4 điều kiện thụ lý từ tài liệu quét OCR',
          },
        },
        {
          id: 'step-kn-2',
          code: 'STEP-KN-02',
          name: 'Xác minh nội dung khiếu nại',
          nodeType: 'TASK',
          isStart: false,
          isEnd: false,
          laneId: 'lane-cv',
          stageId: 'stg-2',
          timeLimitDays: 15,
          workHours: 120,
          warningBeforeHours: 24,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          inheritedFromId: 'std-verify',
          inheritedFromName: 'Bước xác minh thực tế',
          isCustomized: false,
          conditions: [
            'Đã ban hành kế hoạch xác minh nội dung',
            'Thông báo lịch làm việc cho các bên liên quan',
            'Đầy đủ thành phần tổ xác minh theo quyết định',
          ],
          conditionsOverride: false,
          stepForms: ['Biên bản làm việc xác minh thực tế'],
          formsOverride: false,
          inputDocuments: ['Quyết định thành lập đoàn xác minh', 'Hồ sơ tài liệu ban đầu'],
          inputDocsOverride: false,
          storedDocuments: ['Báo cáo xác minh nội dung khiếu nại'],
          outputDocsOverride: false,
          statusChangeDoc: 'Kế hoạch xác minh',
          description: 'Làm việc với người bị khiếu nại, thu thập hồ sơ quyết định hành chính bị khiếu nại.',
          actions: [
            { id: 'act-kn-2-1', code: 'COMPLETE', label: 'Hoàn thành xác minh', type: 'COMPLETE' },
            { id: 'act-kn-2-2', code: 'REQ_MORE', label: 'Yêu cầu cung cấp thêm', type: 'REQUEST_INFO' },
          ],
        },
        {
          id: 'step-kn-3',
          code: 'STEP-KN-03',
          name: 'Tổ chức đối thoại trực tiếp',
          nodeType: 'TASK',
          isStart: false,
          isEnd: false,
          laneId: 'lane-ld',
          stageId: 'stg-3',
          timeLimitDays: 5,
          workHours: 40,
          warningBeforeHours: 8,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          inheritedFromId: 'std-task',
          inheritedFromName: 'Bước xử lý nghiệp vụ',
          isCustomized: false,
          conditions: [
            'Kế hoạch đối thoại được lãnh đạo phê duyệt',
            'Đã gửi giấy mời đối thoại cho công dân trước ít nhất 03 ngày',
          ],
          conditionsOverride: false,
          stepForms: ['Biên bản đối thoại khiếu nại'],
          formsOverride: false,
          inputDocuments: ['Báo cáo kết quả xác minh nội dung khiếu nại'],
          inputDocsOverride: false,
          storedDocuments: ['Biên bản đối thoại giải quyết khiếu nại'],
          outputDocsOverride: false,
          statusChangeDoc: 'Giấy mời đối thoại',
          description: 'Người có thẩm quyền giải quyết chủ trì đối thoại làm rõ yêu cầu của người khiếu nại.',
        },
        {
          id: 'step-kn-4',
          code: 'STEP-KN-04',
          name: 'Dự thảo và ký Quyết định giải quyết',
          nodeType: 'APPROVAL',
          isStart: false,
          isEnd: false,
          laneId: 'lane-ld',
          stageId: 'stg-4',
          timeLimitDays: 5,
          workHours: 40,
          warningBeforeHours: 8,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          inheritedFromId: 'std-approval',
          inheritedFromName: 'Bước trình duyệt / Phê duyệt',
          isCustomized: false,
          conditions: [
            'Đã có biên bản đối thoại thành công hoặc không thành',
            'Dự thảo Quyết định giải quyết đúng căn cứ pháp lý',
          ],
          conditionsOverride: false,
          stepForms: ['Phiếu trình duyệt Quyết định giải quyết khiếu nại'],
          formsOverride: false,
          inputDocuments: ['Biên bản đối thoại', 'Hồ sơ xác minh toàn diện'],
          inputDocsOverride: false,
          storedDocuments: ['Quyết định giải quyết khiếu nại chính thức'],
          outputDocsOverride: false,
          statusChangeDoc: 'Quyết định giải quyết khiếu nại',
          description: 'Ký ban hành Quyết định giải quyết khiếu nại lần đầu hoặc lần hai.',
          approvalConfig: {
            approvalStyle: 'SINGLE',
            authorityRole: 'Chủ tịch UBND / Thủ trưởng cơ quan',
          },
        },
        {
          id: 'step-kn-5',
          code: 'STEP-KN-05',
          name: 'Gửi quyết định và lưu trữ',
          nodeType: 'END',
          isStart: false,
          isEnd: true,
          laneId: 'lane-cv',
          stageId: 'stg-4',
          timeLimitDays: 2,
          workHours: 16,
          warningBeforeHours: 4,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          inheritedFromId: 'std-end',
          inheritedFromName: 'Kết thúc và lưu trữ',
          isCustomized: false,
          conditions: [
            'Quyết định giải quyết đã được đóng dấu/ký số hợp lệ',
            'Đã gửi thông báo cho người khiếu nại và người bị khiếu nại',
          ],
          conditionsOverride: false,
          stepForms: ['Sổ theo dõi giao nhận quyết định giải quyết'],
          formsOverride: false,
          inputDocuments: ['Quyết định giải quyết khiếu nại đã ký'],
          inputDocsOverride: false,
          storedDocuments: ['Sổ giao nhận văn bản gửi đương sự'],
          outputDocsOverride: false,
          statusChangeDoc: 'Đóng hồ sơ khiếu nại',
          description: 'Giao quyết định giải quyết khiếu nại và công khai theo quy định.',
        },
      ],
      transitions: [
        {
          id: 'tr-kn-1',
          actionName: 'Thụ lý xác minh',
          fromStepId: 'step-kn-1',
          toStepId: 'step-kn-2',
          type: 'normal',
          allowedRoles: ['Cán bộ Tiếp dân'],
          createNextTask: true,
          taskAssigneeRole: 'Chuyên viên thụ lý',
          conditions: [],
        },
        {
          id: 'tr-kn-2',
          actionName: 'Lên lịch đối thoại',
          fromStepId: 'step-kn-2',
          toStepId: 'step-kn-3',
          type: 'normal',
          allowedRoles: ['Chuyên viên thụ lý'],
          createNextTask: true,
          taskAssigneeRole: 'Lãnh đạo',
          conditions: [],
        },
        {
          id: 'tr-kn-3',
          actionName: 'Ký quyết định',
          fromStepId: 'step-kn-3',
          toStepId: 'step-kn-4',
          type: 'normal',
          allowedRoles: ['Lãnh đạo'],
          createNextTask: true,
          taskAssigneeRole: 'Lãnh đạo',
          conditions: [],
        },
        {
          id: 'tr-kn-4',
          actionName: 'Phát hành lưu hồ sơ',
          fromStepId: 'step-kn-4',
          toStepId: 'step-kn-5',
          type: 'normal',
          allowedRoles: ['Văn thư'],
          createNextTask: true,
          taskAssigneeRole: 'Văn thư',
          conditions: [],
        },
      ],
      versionHistory: [
        {
          version: 'v1.0',
          publishedAt: 'Mẫu có sẵn',
          publishedBy: 'Hệ thống',
          notes: 'Mẫu quy trình khiếu nại chuẩn',
          isCurrentActive: true,
        },
      ],
    },
  },

  // 3. Quy trình xử lý văn bản / phê duyệt văn bản
  {
    id: 'tpl-van-ban',
    name: 'Quy trình soạn thảo và phê duyệt văn bản',
    codePrefix: 'QT-VB',
    loaiDonId: 'van-ban',
    loaiDonName: 'Văn bản hành chính',
    description: 'Quy trình xử lý văn bản nội bộ: Soạn thảo → Kiểm tra thể thức / Pháp chế → Lãnh đạo ký duyệt → Văn thư ban hành.',
    category: 'VAN_BAN',
    icon: 'description',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    stepsCount: 4,
    lanesCount: 4,
    workflow: {
      id: 'tpl-vb-wf',
      code: 'QT-VB-2026-001',
      name: 'Quy trình soạn thảo và phê duyệt văn bản',
      loaiDonId: 'van-ban',
      loaiDonName: 'Văn bản hành chính',
      version: 'v1.0',
      status: 'draft',
      description: 'Quy trình kiểm soát chất lượng soạn thảo, thẩm định pháp lý và ban hành văn bản quy phạm, chỉ đạo điều hành.',
      updatedAt: '01/10/2026 09:00',
      updatedBy: 'Hệ thống Quản trị',
      lanes: [
        { id: 'lane-st', name: 'Đơn vị Soạn thảo', code: 'ST', order: 1, description: 'Chủ trì dự thảo văn bản' },
        { id: 'lane-pc', name: 'Bộ phận Pháp chế / Thẩm định', code: 'PC', order: 2, description: 'Rà soát căn cứ pháp lý và thể thức' },
        { id: 'lane-ld', name: 'Lãnh đạo ký duyệt', code: 'LD', order: 3, description: 'Ký số văn bản' },
        { id: 'lane-vt', name: 'Văn thư phát hành', code: 'VT', order: 4, description: 'Cấp số, đóng dấu và phát hành' },
      ],
      stages: [
        { id: 'stg-1', name: 'Soạn thảo', order: 1 },
        { id: 'stg-2', name: 'Thẩm định pháp chế', order: 2 },
        { id: 'stg-3', name: 'Ký duyệt', order: 3 },
        { id: 'stg-4', name: 'Phát hành', order: 4 },
      ],
      steps: [
        {
          id: 'step-vb-1',
          code: 'STEP-VB-01',
          name: 'Soạn thảo dự thảo văn bản',
          nodeType: 'START',
          isStart: true,
          isEnd: false,
          laneId: 'lane-st',
          stageId: 'stg-1',
          timeLimitDays: 3,
          workHours: 24,
          warningBeforeHours: 4,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          storedDocuments: ['Bản thảo văn bản Word'],
          stepForms: [],
          statusChangeDoc: 'Dự thảo khởi tạo',
          description: 'Soạn thảo nội dung và đính kèm tờ trình xin chủ trương.',
        },
        {
          id: 'step-vb-2',
          code: 'STEP-VB-02',
          name: 'Kiểm tra thể thức & Thẩm định pháp chế',
          nodeType: 'CHECK',
          isStart: false,
          isEnd: false,
          laneId: 'lane-pc',
          stageId: 'stg-2',
          timeLimitDays: 2,
          workHours: 16,
          warningBeforeHours: 4,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          storedDocuments: ['Phiếu góp ý thẩm định pháp lý'],
          stepForms: [],
          statusChangeDoc: 'Văn bản đã thẩm định',
          description: 'Thẩm định căn cứ pháp lý, kỹ thuật soạn thảo văn bản quy phạm.',
        },
        {
          id: 'step-vb-3',
          code: 'STEP-VB-03',
          name: 'Lãnh đạo ký số phê duyệt',
          nodeType: 'APPROVAL',
          isStart: false,
          isEnd: false,
          laneId: 'lane-ld',
          stageId: 'stg-3',
          timeLimitDays: 2,
          workHours: 16,
          warningBeforeHours: 4,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          storedDocuments: ['Văn bản ký số PDF'],
          stepForms: [],
          statusChangeDoc: 'Văn bản đã ký duyệt',
          description: 'Ký số cá nhân / tổ chức phê duyệt ban hành.',
        },
        {
          id: 'step-vb-4',
          code: 'STEP-VB-04',
          name: 'Cấp số, đóng dấu & Phát hành văn bản',
          nodeType: 'END',
          isStart: false,
          isEnd: true,
          laneId: 'lane-vt',
          stageId: 'stg-4',
          timeLimitDays: 1,
          workHours: 8,
          warningBeforeHours: 2,
          workSchedule: 'Giờ hành chính (8h-17h, Thứ 2 - Thứ 6)',
          storedDocuments: ['Văn bản số chính thức đã vào sổ'],
          stepForms: [],
          statusChangeDoc: 'Phát hành hoàn tất',
          description: 'Đăng ký vào sổ công văn đi và gửi qua Trục liên thông văn bản quốc gia.',
        },
      ],
      transitions: [
        {
          id: 'tr-vb-1',
          actionName: 'Chuyển pháp chế',
          fromStepId: 'step-vb-1',
          toStepId: 'step-vb-2',
          type: 'normal',
          allowedRoles: ['Chuyên viên soạn thảo'],
          createNextTask: true,
          taskAssigneeRole: 'Pháp chế',
          conditions: [],
        },
        {
          id: 'tr-vb-2',
          actionName: 'Trình ký duyệt',
          fromStepId: 'step-vb-2',
          toStepId: 'step-vb-3',
          type: 'normal',
          allowedRoles: ['Pháp chế'],
          createNextTask: true,
          taskAssigneeRole: 'Lãnh đạo',
          conditions: [],
        },
        {
          id: 'tr-vb-3',
          actionName: 'Chuyển phát hành',
          fromStepId: 'step-vb-3',
          toStepId: 'step-vb-4',
          type: 'normal',
          allowedRoles: ['Lãnh đạo'],
          createNextTask: true,
          taskAssigneeRole: 'Văn thư',
          conditions: [],
        },
      ],
      versionHistory: [
        {
          version: 'v1.0',
          publishedAt: 'Mẫu có sẵn',
          publishedBy: 'Hệ thống',
          notes: 'Mẫu quy trình văn bản',
          isCurrentActive: true,
        },
      ],
    },
  },

  // 4. Quy trình kiến nghị / phản ánh
  {
    id: 'tpl-kien-nghi',
    name: 'Quy trình xử lý kiến nghị / phản ánh',
    codePrefix: 'QT-KNPA',
    loaiDonId: 'kien-nghi',
    loaiDonName: 'Kiến nghị, phản ánh',
    description: 'Quy trình giải quyết nhanh kiến nghị của công dân: Tiếp nhận trực tuyến → Chuyển đơn vị trực thuộc → Trả lời công khai trên Cổng DVC.',
    category: 'DON_THU',
    icon: 'chat',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    stepsCount: 3,
    lanesCount: 3,
    workflow: {
      id: 'tpl-knpa-wf',
      code: 'QT-KNPA-2026-001',
      name: 'Quy trình tiếp nhận và xử lý kiến nghị, phản ánh',
      loaiDonId: 'kien-nghi',
      loaiDonName: 'Kiến nghị, phản ánh',
      version: 'v1.0',
      status: 'draft',
      description: 'Quy trình tiếp nhận phản ánh kiến nghị của người dân và doanh nghiệp.',
      updatedAt: '01/10/2026 09:30',
      updatedBy: 'Hệ thống Quản trị',
      lanes: [
        { id: 'lane-cpc', name: 'Tổng đài / Cổng DVC', code: 'TD', order: 1, description: 'Bộ phận tiếp nhận phản ánh' },
        { id: 'lane-cm', name: 'Đơn vị chuyên trách', code: 'CM', order: 2, description: 'Kiểm tra xử lý thực địa' },
        { id: 'lane-ld', name: 'Trưởng ban điều hành', code: 'TB', order: 3, description: 'Duyệt phản hồi công dân' },
      ],
      stages: [
        { id: 'stg-1', name: 'Tiếp nhận phản ánh', order: 1 },
        { id: 'stg-2', name: 'Xử lý thực tế', order: 2 },
        { id: 'stg-3', name: 'Công khai kết quả', order: 3 },
      ],
      steps: [
        {
          id: 'step-pa-1',
          code: 'STEP-PA-01',
          name: 'Tiếp nhận phản ánh từ Cổng DVC',
          nodeType: 'START',
          isStart: true,
          isEnd: false,
          laneId: 'lane-cpc',
          stageId: 'stg-1',
          timeLimitDays: 1,
          workHours: 8,
          warningBeforeHours: 2,
          workSchedule: 'Hành chính (8h-17h, Thứ 2 - Thứ 6)',
          storedDocuments: ['Phiếu ghi nhận phản ánh kiến nghị'],
          stepForms: [],
          statusChangeDoc: 'Tiếp nhận phản ánh',
          description: 'Tự động đồng bộ và vào sổ các phản ánh gửi từ người dân.',
        },
        {
          id: 'step-pa-2',
          code: 'STEP-PA-02',
          name: 'Kiểm tra hiện trường & Khắc phục',
          nodeType: 'TASK',
          isStart: false,
          isEnd: false,
          laneId: 'lane-cm',
          stageId: 'stg-2',
          timeLimitDays: 5,
          workHours: 40,
          warningBeforeHours: 8,
          workSchedule: 'Hành chính (8h-17h, Thứ 2 - Thứ 6)',
          storedDocuments: ['Hình ảnh hiện trường', 'Biên bản xử lý khắc phục'],
          stepForms: [],
          statusChangeDoc: 'Báo cáo kết quả xử lý',
          description: 'Cán bộ xuống địa bàn kiểm tra và xử lý kiến nghị.',
        },
        {
          id: 'step-pa-3',
          code: 'STEP-PA-03',
          name: 'Duyệt và gửi câu trả lời cho công dân',
          nodeType: 'NOTIFICATION',
          isStart: false,
          isEnd: true,
          laneId: 'lane-ld',
          stageId: 'stg-3',
          timeLimitDays: 1,
          workHours: 8,
          warningBeforeHours: 2,
          workSchedule: 'Hành chính (8h-17h, Thứ 2 - Thứ 6)',
          storedDocuments: ['Nội dung câu trả lời công dân'],
          stepForms: [],
          statusChangeDoc: 'Hoàn thành trả lời',
          description: 'Đăng tải câu trả lời lên Cổng DVC và gửi tin nhắn SMS cho người dân.',
        },
      ],
      transitions: [
        {
          id: 'tr-pa-1',
          actionName: 'Chuyển đơn vị xử lý',
          fromStepId: 'step-pa-1',
          toStepId: 'step-pa-2',
          type: 'normal',
          allowedRoles: ['Tổng đài viên'],
          createNextTask: true,
          taskAssigneeRole: 'Đơn vị chuyên trách',
          conditions: [],
        },
        {
          id: 'tr-pa-2',
          actionName: 'Trình duyệt kết quả',
          fromStepId: 'step-pa-2',
          toStepId: 'step-pa-3',
          type: 'normal',
          allowedRoles: ['Đơn vị chuyên trách'],
          createNextTask: true,
          taskAssigneeRole: 'Trưởng ban điều hành',
          conditions: [],
        },
      ],
      versionHistory: [
        {
          version: 'v1.0',
          publishedAt: 'Mẫu có sẵn',
          publishedBy: 'Hệ thống',
          notes: 'Mẫu quy trình kiến nghị',
          isCurrentActive: true,
        },
      ],
    },
  },
  // 5. Quy trình tiếp nhận & xử lý tố giác, tin báo về tội phạm tại Công an cấp xã (8 bước chuẩn)
  {
    id: 'tpl-to-giac-cax',
    name: 'Quy trình xử lý tố giác/tin báo về tội phạm tại Công an cấp xã',
    codePrefix: 'QT-TG-CAX',
    loaiDonId: 'to-giac',
    loaiDonName: 'Tố giác / Tin báo về tội phạm',
    description: 'Quy trình chuẩn hóa 8 bước gồm bước Lập báo cáo xác minh (bước 5) và Kiểm tra hoàn thiện (bước 6) theo quy định tại TTLT 01/2021 & BLTTHS 2015.',
    category: 'DON_THU',
    icon: 'local_police',
    badgeColor: 'bg-rose-100 text-rose-800 border-rose-200',
    stepsCount: 8,
    lanesCount: 4,
    workflow: {
      id: 'tpl-to-giac-cax-wf',
      code: 'QT-TG-CAX-2026-001',
      name: 'Quy trình tiếp nhận và xử lý tố giác/tin báo về tội phạm tại Công an cấp xã',
      loaiDonId: 'to-giac',
      loaiDonName: 'Tố giác / Tin báo về tội phạm',
      version: 'v1.0',
      status: 'published',
      description: 'Quy trình 8 bước chuẩn hóa tiếp nhận, kiểm tra ban đầu, xác minh, lập báo cáo xác minh, kiểm tra hoàn thiện, đề xuất xử lý và bàn giao.',
      updatedAt: '19/09/2026 09:00',
      updatedBy: 'Hệ thống Quản trị Quy trình Công an',
      lanes: [
        { id: 'lane-tb', name: 'Trực ban / Tiếp nhận Công an cấp xã', code: 'TB', order: 1, description: 'Tiếp nhận tố giác/tin báo và vào sổ theo dõi' },
        { id: 'lane-cb', name: 'Cán bộ thụ lý / Tổ xác minh Công an xã', code: 'CB', order: 2, description: 'Kiểm tra ban đầu, xác minh và lập báo cáo' },
        { id: 'lane-ch', name: 'Chỉ huy / Phó Trưởng Công an cấp xã', code: 'CH', order: 3, description: 'Kiểm tra, hoàn thiện báo cáo xác minh' },
        { id: 'lane-tr', name: 'Trưởng Công an cấp xã', code: 'TR', order: 4, description: 'Xem xét báo cáo, phê duyệt đề xuất và quyết định' },
      ],
      stages: [
        { id: 'stg-1', name: 'Tiếp nhận & Kiểm tra ban đầu', order: 1 },
        { id: 'stg-2', name: 'Xác minh & Ghi nhận kết quả', order: 2 },
        { id: 'stg-3', name: 'Lập báo cáo xác minh', order: 3 },
        { id: 'stg-4', name: 'Kiểm tra & Hoàn thiện báo cáo', order: 4 },
        { id: 'stg-5', name: 'Đề xuất hướng xử lý & Bàn giao', order: 5 },
      ],
      steps: [
        {
          id: 'step-cax-1',
          code: 'STEP-01',
          name: 'Tiếp nhận tố giác/tin báo',
          nodeType: 'START',
          isStart: true,
          isEnd: false,
          laneId: 'lane-tb',
          stageId: 'stg-1',
          timeLimitDays: 1,
          workHours: 8,
          warningBeforeHours: 2,
          workSchedule: 'Trực ban 24/7',
          storedDocuments: ['Biên bản tiếp nhận tố giác/tin báo', 'Giấy biên nhận'],
          stepForms: ['BM-01/TN Biên bản tiếp nhận'],
          statusChangeDoc: 'Tiếp nhận thành công',
          description: 'Tiếp nhận thông tin từ công dân/cơ quan, vào sổ tiếp nhận điện tử và cấp giấy biên nhận.',
          actions: [{ id: 'act-cax-1', code: 'CHUYEN_KIEM_TRA', label: 'Chuyển kiểm tra', type: 'COMPLETE' }],
        },
        {
          id: 'step-cax-2',
          code: 'STEP-02',
          name: 'Kiểm tra ban đầu, đọc hiểu nội dung & tra cứu',
          nodeType: 'TASK',
          isStart: false,
          isEnd: false,
          laneId: 'lane-cb',
          stageId: 'stg-1',
          timeLimitDays: 2,
          workHours: 16,
          warningBeforeHours: 4,
          workSchedule: 'Giờ hành chính',
          storedDocuments: ['Phiếu phân loại sơ bộ', 'Bản trích lục tra cứu CSDL'],
          stepForms: ['BM-02/KT Phiếu kiểm tra ban đầu'],
          statusChangeDoc: 'Đang kiểm tra sơ bộ',
          description: 'Đọc hiểu nội dung, đối soát chứng cứ, tra cứu dữ liệu dân cư và tiền sử đơn thư.',
          actions: [{ id: 'act-cax-2', code: 'TIEN_HANH_XM', label: 'Thực hiện xác minh', type: 'COMPLETE' }],
        },
        {
          id: 'step-cax-3',
          code: 'STEP-03',
          name: 'Xác định hướng xử lý & Thực hiện hoạt động xác minh',
          nodeType: 'TASK',
          isStart: false,
          isEnd: false,
          laneId: 'lane-cb',
          stageId: 'stg-2',
          timeLimitDays: 5,
          workHours: 40,
          warningBeforeHours: 8,
          workSchedule: 'Giờ hành chính',
          storedDocuments: ['Kế hoạch xác minh', 'Giấy mời làm việc'],
          stepForms: ['BM-03/KH Kế hoạch kiểm tra xác minh'],
          statusChangeDoc: 'Đang xác minh thực tế',
          description: 'Mời đương sự làm việc, lấy lời khai, kiểm tra hiện trường sơ bộ theo thẩm quyền.',
          actions: [{ id: 'act-cax-3', code: 'GHI_NHAN_KQ', label: 'Ghi nhận kết quả', type: 'COMPLETE' }],
        },
        {
          id: 'step-cax-4',
          code: 'STEP-04',
          name: 'Ghi nhận kết quả xác minh & Cập nhật tài liệu',
          nodeType: 'TASK',
          isStart: false,
          isEnd: false,
          laneId: 'lane-cb',
          stageId: 'stg-2',
          timeLimitDays: 2,
          workHours: 16,
          warningBeforeHours: 4,
          workSchedule: 'Giờ hành chính',
          storedDocuments: ['Biên bản lấy lời khai', 'Biên bản kiểm tra thực địa', 'Biên bản niêm phong'],
          stepForms: ['BM-04/BB Biên bản làm việc'],
          statusChangeDoc: 'Đã có kết quả xác minh',
          description: 'Lập biên bản làm việc, số hóa tài liệu đồ vật, kiểm đếm và bảo quản chứng cứ.',
          actions: [{ id: 'act-cax-4', code: 'LAP_BAO_CAO', label: 'Lập báo cáo xác minh', type: 'COMPLETE' }],
        },
        {
          id: 'step-cax-5',
          code: 'STEP-05',
          name: 'Lập báo cáo xác minh',
          nodeType: 'TASK',
          isStart: false,
          isEnd: false,
          laneId: 'lane-cb',
          stageId: 'stg-3',
          timeLimitDays: 2,
          workHours: 16,
          warningBeforeHours: 4,
          workSchedule: 'Giờ hành chính',
          storedDocuments: ['Báo cáo kết quả kiểm tra, xác minh (Dự thảo)'],
          stepForms: ['BM-05/BC Báo cáo xác minh nguồn tin'],
          statusChangeDoc: 'Đã lập báo cáo xác minh',
          description: 'Tự động tổng hợp thông tin, liên kết tài liệu căn cứ, biên tập nội dung và xác nhận báo cáo.',
          actions: [{ id: 'act-cax-5', code: 'TRINH_KIEM_TRA', label: 'Trình kiểm tra', type: 'APPROVE' }],
        },
        {
          id: 'step-cax-6',
          code: 'STEP-06',
          name: 'Kiểm tra, hoàn thiện báo cáo & Trình người có thẩm quyền',
          nodeType: 'TASK',
          isStart: false,
          isEnd: false,
          laneId: 'lane-ch',
          stageId: 'stg-4',
          timeLimitDays: 1,
          workHours: 8,
          warningBeforeHours: 2,
          workSchedule: 'Giờ hành chính',
          storedDocuments: ['Phiếu kiểm tra báo cáo', 'Báo cáo xác minh hoàn thiện'],
          stepForms: ['BM-06/PT Phiếu trình kiểm tra'],
          statusChangeDoc: 'Chờ duyệt quyết định',
          description: 'Chỉ huy/Phó Trưởng Công an xã rà soát hồ sơ, hoàn thiện báo cáo và lập phiếu trình Trưởng Công an xã.',
          actions: [
            { id: 'act-cax-6a', code: 'DONG_Y_TRINH', label: 'Đồng ý trình', type: 'APPROVE' },
            { id: 'act-cax-6b', code: 'YEU_CAU_SUA', label: 'Yêu cầu sửa đổi', type: 'RETURN' },
          ],
        },
        {
          id: 'step-cax-7',
          code: 'STEP-07',
          name: 'Lập báo cáo đề xuất hướng xử lý & Trình quyết định',
          nodeType: 'TASK',
          isStart: false,
          isEnd: false,
          laneId: 'lane-cb',
          stageId: 'stg-5',
          timeLimitDays: 2,
          workHours: 16,
          warningBeforeHours: 4,
          workSchedule: 'Giờ hành chính',
          storedDocuments: ['Báo cáo đề xuất hướng xử lý', 'Dự thảo văn bản chuyển cơ quan điều tra'],
          stepForms: ['BM-07/DX Báo cáo đề xuất xử lý'],
          statusChangeDoc: 'Đã trình đề xuất xử lý',
          description: 'Lập báo cáo đề xuất hướng xử lý độc lập (chuyển CQĐT cấp huyện / xử phạt hành chính) trình Lãnh đạo ký duyệt.',
          actions: [{ id: 'act-cax-7', code: 'KY_DUYET', label: 'Trưởng CA xã ký duyệt', type: 'APPROVE' }],
        },
        {
          id: 'step-cax-8',
          code: 'STEP-08',
          name: 'Ghi nhận quyết định & Bàn giao luồng tiếp theo',
          nodeType: 'END',
          isStart: false,
          isEnd: true,
          laneId: 'lane-tr',
          stageId: 'stg-5',
          timeLimitDays: 1,
          workHours: 8,
          warningBeforeHours: 2,
          workSchedule: 'Giờ hành chính',
          storedDocuments: ['Quyết định / Công văn chuyển nguồn tin', 'Biên bản bàn giao hồ sơ vật chứng'],
          stepForms: ['BM-08/BG Biên bản bàn giao'],
          statusChangeDoc: 'Hoàn tất quy trình cấp xã',
          description: 'Ghi nhận quyết định của Lãnh đạo; bàn giao hồ sơ vật chứng cho Cơ quan CSĐT thẩm quyền; thông báo cho công dân.',
          actions: [{ id: 'act-cax-8', code: 'HOAN_TAT', label: 'Hoàn tất & Đóng hồ sơ', type: 'COMPLETE' }],
        },
      ],
      transitions: [
        { id: 'tr-cax-1', actionName: 'Chuyển kiểm tra ban đầu', fromStepId: 'step-cax-1', toStepId: 'step-cax-2', type: 'normal', allowedRoles: ['Trực ban'], createNextTask: true, taskAssigneeRole: 'Cán bộ thụ lý', conditions: [] },
        { id: 'tr-cax-2', actionName: 'Tiến hành xác minh', fromStepId: 'step-cax-2', toStepId: 'step-cax-3', type: 'normal', allowedRoles: ['Cán bộ thụ lý'], createNextTask: true, taskAssigneeRole: 'Tổ xác minh', conditions: [] },
        { id: 'tr-cax-3', actionName: 'Ghi nhận kết quả', fromStepId: 'step-cax-3', toStepId: 'step-cax-4', type: 'normal', allowedRoles: ['Tổ xác minh'], createNextTask: true, taskAssigneeRole: 'Cán bộ thụ lý', conditions: [] },
        { id: 'tr-cax-4', actionName: 'Khởi tạo Báo cáo xác minh', fromStepId: 'step-cax-4', toStepId: 'step-cax-5', type: 'normal', allowedRoles: ['Cán bộ thụ lý'], createNextTask: true, taskAssigneeRole: 'Cán bộ thụ lý', conditions: [] },
        { id: 'tr-cax-5', actionName: 'Trình kiểm tra hoàn thiện', fromStepId: 'step-cax-5', toStepId: 'step-cax-6', type: 'normal', allowedRoles: ['Cán bộ thụ lý'], createNextTask: true, taskAssigneeRole: 'Chỉ huy / Phó Trưởng CAX', conditions: [] },
        { id: 'tr-cax-6', actionName: 'Đồng ý & Chuyển lập đề xuất', fromStepId: 'step-cax-6', toStepId: 'step-cax-7', type: 'normal', allowedRoles: ['Phó Trưởng CAX'], createNextTask: true, taskAssigneeRole: 'Cán bộ thụ lý', conditions: [] },
        { id: 'tr-cax-6b', actionName: 'Yêu cầu xác minh bổ sung', fromStepId: 'step-cax-6', toStepId: 'step-cax-5', type: 'return', allowedRoles: ['Phó Trưởng CAX'], createNextTask: true, taskAssigneeRole: 'Cán bộ thụ lý', conditions: [] },
        { id: 'tr-cax-7', actionName: 'Ký duyệt & Chuyển bàn giao', fromStepId: 'step-cax-7', toStepId: 'step-cax-8', type: 'normal', allowedRoles: ['Trưởng Công an cấp xã'], createNextTask: true, taskAssigneeRole: 'Trực ban / Văn thư', conditions: [] },
      ],
      versionHistory: [
        {
          version: 'v1.0',
          publishedAt: '01/10/2026',
          publishedBy: 'Quản trị viên',
          notes: 'Ban hành quy trình chuẩn 8 bước bổ sung Bước 5 Lập báo cáo xác minh',
          isCurrentActive: true,
        },
      ],
    },
  },
];
